### ISSUE TITLE
chrome vs chromium

### ISSUE THREAD

**Issue by awb99** [giggio/node-chromedriver#101]
I am running arch linux; and got it running with chromium. 
I wonder if I can set it to work with chrome instead. 

Why is this relevant? I want to use the headless feature, and when I try to install chromium-dev then it somehow never completes the installation.

Andreas

**Comment by giggio** [comment]
I have no idea how Chromedriver picks the Chrome or Chromedriver instance. You probably can set some argument on the `start` method.

BTW: Headless is out now with Chrome 59.
