### ISSUE TITLE
Chromedriver installation is trying to access https url

### ISSUE THREAD

**Issue by nareshsurya** [giggio/node-chromedriver#104]
Hi Team,
I'm facing an issue while installing chromedriver node module in a VM which doesn't have internet access.
We have a requirement that we need to install node modules from our internal artifactory which will be accessed in my VM. So far I'm able to install node modules like protractor, jasmine, webdriver, xlsx etc 
As this chromedriver nodemodule installation internally trying to access https url , I'm having issue with this installation.
![image](https://cloud.githubusercontent.com/assets/12846126/26351313/c8069af8-3fd4-11e7-9388-6e9b3627a624.png)

Note: 1. I was able to install until 2.25.1
          2. My VM have an access to internal sites.

Can someone please look into it and suggest a way to get around?

Regards,
Naresh Surya

**Comment by nareshsurya** [comment]
Can anyone please look into it and do the needful?

**Comment by giggio** [comment]
You can use `chromedriver_cdnurl` as explained on the readme or `chromedriver_filepath` (set it to the downloaded zip file).
