### ISSUE TITLE
Latest version not parsed correctly

### ISSUE THREAD

**Issue by 153957** [giggio/node-chromedriver#106]
Currently the latest version is 2.30. So I tried installing the chromedriver using `chromedriver_version=LATEST`.
This retrieves the version from http://chromedriver.storage.googleapis.com/LATEST_RELEASE
This only contains `2.30`, which is then parsed as JSON: https://github.com/giggio/node-chromedriver/blob/master/install.js#L164

Which results in the float `2.3`:
```
...
Output:
Downloading https://chromedriver.storage.googleapis.com/2.3/chromedriver_mac64.zip
Saving to /var/folders/q1/0zmwsr7j6zlfr4tgn/T/chromedriver/chromedriver_mac64.zip
Received 0K total.
Extracting zip contents
ChromeDriver installation failed Error extracting archive:
 Error: end of central directory record signature not found
```

So instead of parsing the LATEST_RELEASE as JSON it should be taken as string.

**Comment by giggio** [comment]
It works on Windows, because the version exists, but I get version `2.3` instead of `2.30`. Bug confirmed.

**Comment by giggio** [comment]
@153957 I updated the package to `2.30`, so you can get the latest version until we fix this.

**Comment by giggio** [comment]
Version `2.30.1` published to NPM with the problem in `LATEST` solved.
