### ISSUE TITLE
2.31 is out

### ISSUE THREAD

**Issue by fatso83** [giggio/node-chromedriver#111]
[Contains the fix](https://npm.taobao.org/mirrors/chromedriver/2.31/notes.txt) that finally makes X and `xvfb-run` superfluous.

**Comment by alippai** [comment]
Added PR for this: https://github.com/giggio/node-chromedriver/pull/112

**Comment by giggio** [comment]
Closed on #112.

**Comment by giggio** [comment]
Published to NPM just now.

**Comment by alippai** [comment]
Awesome, thank you.
