### ISSUE TITLE
Should I see a chrome window?

### ISSUE THREAD

**Issue by Madd0g** [giggio/node-chromedriver#118]
I do not see the chrome window open when I run my tests, is that expected? I'm not running in headless mode.

Is there a way to show the window?

Thanks

**Comment by giggio** [comment]
By default you should see Chrome opening, you should see its window. The way you do it depends on the parameters you pass to it. This library only controls the install and start up of Chromedriver. You should talk to the Chromedriver team on how to do what you need, or maybe search on their docs. If you are using Selenium, you could check their docs as well.
