### ISSUE TITLE
support question  - how to use with Protractor

### ISSUE THREAD

**Issue by ORESoftware** [giggio/node-chromedriver#125]
Anybody happen to know how to use this module with Protractor (AngularJS)?

thanks

**Comment by mdbarr** [comment]
Yes, it's a one line addition to the Protractor (v5.1.2) config file if you
are using direct connect, e.g.

const PROJECT_ROOT = '...'

exports.config = {

  directConnect: true,

  capabilities: {

    browserName: 'chrome',

    chromeOptions: { ... }

  },

  chromeDriver: PROJECT_ROOT +
'/node_modules/chromedriver/bin/chromedriver',

  framework: 'jasmine2',

  ...

-Mark
