### ISSUE TITLE
chromedriver is not packaged in electron-builder installer

### ISSUE THREAD

**Issue by JPaulPunzalan** [giggio/node-chromedriver#128]
Hi,

`chromedriver` and other browser drivers are **not packaged** into the `Windows installer` that was generated using `electron-builder`, resulting for the `require('chromedriver')` code to crash the test script when ran using the `Electron` app.

Is there a workaround for this?

Thanks!

**Comment by giggio** [comment]
@JPaulPunzalan I am not sure I understand your problem. I am not familiar with `electron-builder` or how it works. Can you share more details on the problem?
