### ISSUE TITLE
Working with Chrome installed in non-standard location

### ISSUE THREAD

**Issue by snoblenet** [giggio/node-chromedriver#129]
On Bamboo, I'm installing Google Chrome to `/chrome/latest/chrome.`

I don't have permission to create a symlink from that location to `/usr/bin/google-chrome`.

Chromedriver apparently lets you do something like:

```
ChromeOptions options = new ChromeOptions();
options.setBinary("/path/to/other/chrome/binary");
```

With your tool, would I do something like `chromedriver.start({ setBinary: '/chrome/latest/chrome' })`?

Thanks.

**Comment by giggio** [comment]
This is set using WebDriver, not directly on ChromeDriver. More info: https://sites.google.com/a/chromium.org/chromedriver/getting-started
