### ISSUE TITLE
Bad error message when chrome is not installed

### ISSUE THREAD

**Issue by strike5150** [giggio/node-chromedriver#130]
`  { stacktrace: 'org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.32.498513 `

This is the error message you get when chrome is not installed on the system.  Along with a whole lot of other misleading information.  This should really say that chromedriver is a wrapper and can't find chrome installed on the system.

I believe a lot of people run into this and go looking for other unrelated issues.

**Comment by giggio** [comment]
This is not a problem with this package, which just install Chromdriver, but with ChromeDriver itself. You should open that issue on their issue tracker.
