### ISSUE TITLE
Get status? How to debug error?

### ISSUE THREAD

**Issue by thebarty** [giggio/node-chromedriver#132]
Hi guys,

**2 questions:**
1) Is there a way to check status of chromedriver AFTER running `chromedriver.start()`?
2) Where can I see some logs in case of errors, expecially on ubuntu?

BACKGROUND:
My setup works perfectly on my macbook, BUT I am having problems on production (a 1GB RAM digitalocean container). 

I have chromedriver hooked up with webdriverio and am getting a "'A session id is required for this command but wasn\'t found in the response payload"-error and "Error: Couldn't connect to selenium server".

**Comment by giggio** [comment]
Start will return a `ChildProcess`, as it is returning a call to `execFile` as you can see here:
https://github.com/giggio/node-chromedriver/blob/700ba5397aef18ae67427583b2cc56e7d8edb810/lib/chromedriver.js#L6

From there you can interact with the process.

More info:
https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

**Comment by thebarty** [comment]
Nice! Thanks for the answer.

In my case what helped me was a 
1) `console.log` of the whole chromedriver-object AFTER runnin `chromedriver.start`. This way you find out WHERE chromedriver is located in the filesystem
2) log into server and try to run chromedriver vie bash. This revealed an error for me "error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory" and I added "apt-get install libnss3-dev -y --force-yes" to my setup-script

**Comment by thebarty** [comment]
Hmmm. I am still having problems using chromedriver with webdriverio.

@giggio Are there any log files (maybe of chromedriver) that I could look at?

**Comment by giggio** [comment]
@thebarty you can start chromedriver directly from the terminal, you can check the logs there.
