### ISSUE TITLE
Allow for different versions of chromedriver to be downloaded

### ISSUE THREAD

**Issue by simonatorw** [giggio/node-chromedriver#134]
I have older browser and can't upgrade

**Comment by giggio** [comment]
Just use an older npm package version, ie:

```bash
npm i chromedriver@2.30
```

or like that:

```bash
npm install chromedriver --chromedriver_version=2.30
```

This is in the README.

**Comment by simonatorw** [comment]
I've tried but I think the selenium webdriver does not like it and
it's hard to find the version of it to work with an older driver.

On 12/26/17, Giovanni Bassi <notifications@github.com> wrote:
> Just use an older npm package version, ie:
>
> ```bash
> npm i chromedriver@2.30
> ```
>
> or like that:
>
> ```bash
> npm install chromedriver --chromedriver_version=2.30
> ```
>
> This is in the README.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/giggio/node-chromedriver/issues/134#issuecomment-353976357


-- 
Can fat ppl fly on the halfpipe?  I replied, "How high?"
