### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by xcs-go** [giggio/node-chromedriver#135]
when i use vue-cli to install a vue progress.the terminal show:
ChromeDriver installation failed Error with http(s) request: Error: read ETIMEDOUT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.34.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.34.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

what should i do?

**Comment by tlorenzi** [comment]
I have been having the same exact issue for the past two days. Does anyone know how to fix this?

**Comment by xcs-go** [comment]
I use this way to install chromedriver, but it is only useful in China. Maybe you can try it. Good luck to you
npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver

**Comment by giggio** [comment]
Your connection is timing out, this is not related to this module.
