### ISSUE TITLE
Install fails for Linux on 32 bits and version 2.34

### ISSUE THREAD

**Issue by rh-programm** [giggio/node-chromedriver#136]
Hello,
When I run the `npm install chromedriver` command, I get the following messages:

> `frappe@rh-programm:~$ npm install chromedriver`
> 
> `> chromedriver@2.34.0 install /home/frappe/node_modules/chromedriver`
> `> node install.js`
>
> `Downloading https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux32.zip`
> `Saving to /tmp/chromedriver/chromedriver_linux32.zip`
> `Received 0K total.`
> `Extracting zip contents`
> `ChromeDriver installation failed Error extracting archive: Error: end of central directory record signature not found`
> `npm WARN enoent ENOENT: no such file or directory, open '/home/frappe/package.json'`
> `npm WARN frappe No description`
> `npm WARN frappe No repository field.`
> `npm WARN frappe No README data`
> `npm WARN frappe No license field.`
> 
> `npm ERR! code ELIFECYCLE`
> `npm ERR! errno 1`
> `npm ERR! chromedriver@2.34.0 install: 'node install.js'`
> `npm ERR! Exit status 1`
> `npm ERR!`
> `npm ERR! Failed at the chromedriver@2.34.0 install script.`
> `npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
> 
> `npm ERR! A complete log of this run can be found in:`
> `npm ERR!     /home/frappe/.npm/_logs/2018-01-01T20_43_43_094Z-debug.log`

**Comment by giggio** [comment]
It looks like that they are not supporting 32 bits on Linux anymore.
This are the 2.33 files:
https://chromedriver.storage.googleapis.com/index.html?path=2.33/
This are the 2.34 files:
https://chromedriver.storage.googleapis.com/index.html?path=2.34/

We need to make sure, because if this is correct we have to update the code to fail on a 32 bit Linux system.

**Comment by giggio** [comment]
I just found out that 32 bits has been discontinued: https://groups.google.com/d/msg/chromedriver-users/JZUYvp_xr60/pyTRBxv1CwAJ

**Comment by giggio** [comment]
Published version `2.34.1` to npm, and it will explicitly fail on Linux 32 bits.
