### ISSUE TITLE
How to disable log DevTools listening...

### ISSUE THREAD

**Issue by JaLe29** [giggio/node-chromedriver#140]
Hello,

how can I disable logs from chrome driver?

After start, I am getting some messages, for example:

DevTools listening on ws://127.0.0.1:12435/devtools/browser/87ee1f8a-39fe-4b50-85c4-5b3938d97e46

Thanks for help.

**Comment by mdbarr** [comment]
Add --disable-extensions to the set of chrome args to disable the devtools.
If you are using protractor, that would go into the config file as follows:

exports.config = {
  directConnect: true,

  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        '--disable-extensions'

Thanks,
-Mark

**Comment by JaLe29** [comment]
Hi Mark, 

thank you for your reply, but it doesn't work. I have still log message 'DevTools listening on ws:.....'

Full code:

```
                require('chromedriver')
                const webdriver = require('selenium-webdriver')
                const { By } = require('selenium-webdriver')

		const CHROME_OPTIONS = {
			'args': [
				'--disable-extensions',
			],
			'prefs': {
				'profile.managed_default_content_settings.images': 2,
			},
		}
		let chromeCapabilities = webdriver.Capabilities.chrome()
		chromeCapabilities.set('chromeOptions', CHROME_OPTIONS)

		this.driver = new webdriver.Builder()
			.forBrowser('chrome')
			.withCapabilities(chromeCapabilities)
			.build()
```

> 		"chromedriver": "^2.33.1",
> 		"selenium-webdriver": "^3.6.0"

Win 10, 64b.

**Comment by mdbarr** [comment]
It could be one of these other options, the full set we use in our testing
is:
    '--ignore-gpu-blacklist',
    '--no-default-browser-check',
    '--no-first-run',
    '--disable-default-apps',
    '--disable-infobars',
    '--disable-extensions',
    '--test-type'

Thanks,
-Mark

**Comment by JaLe29** [comment]
I tried all and problem is still the same.
Still 'DevTools listening on ws:....' in console :-(

**Comment by giggio** [comment]
@JaLe29 this would be an issue with chromedriver itself, not with this package. This package only install chromedriver. I suggest you open an issue directly on their issue tracker.

**Comment by mohyeid** [comment]
I am having the same issue. Did you have any luck?

**Comment by JaLe29** [comment]
@mohyeid nope

**Comment by ArcherBG** [comment]
Has anyone found a working solution?

**Comment by giggio** [comment]
Please discuss this on the Chromedriver repo, not this one.
