### ISSUE TITLE
url command fails when transitioning to a hash url

### ISSUE THREAD

**Issue by jhoguet** [giggio/node-chromedriver#141]
## The problem

Using webdriver.io, I am unable to use `browser.url()` to go to a hash of the current page. 

Using `chromedriver@2.35.0` and `chrome@64.0.3282.119` I am NOT able to go to the second page. Chromedriver never responds. 

Using `chromedriver@2.35.0` with `chrome@63.0.3239.108` I am able to go to the second page. Suggesting maybe it was in the `chrome@64` release. 

Using `chromedriver@2.33.2` with `chrome@64.0.3282.119`  I am able to go to the second page. Suggesting maybe it was in the `chromedriver@2.34+` release. 

This issue is a deviation of the original posted on webdriverio (https://github.com/webdriverio/webdriverio/issues/2575#issuecomment-362020254) 

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: v7.10.1
* chromedriver@2.35.0
* chrome@64.0.3282.119

## Details

Recently we noticed our tests started blocking. They would navigate to the page we requested, but the promise would not resolve or reject. We isolated this to when we were using `browser.url()` to go to a hash url. 

Here we can see it getting to the page we requested

![image](https://user-images.githubusercontent.com/1234146/35633806-28ddab0e-0678-11e8-9843-fece73d1c599.png)

and the webdriverio logs 
```
[11:15:35]  COMMAND	POST 	 "/session/e00594537a51dcfd2c610cdad8f89d8c/url"
[11:15:35]  DATA		{"url":"https://en.wikipedia.org/wiki/Cat"}
[11:15:37]  COMMAND	POST 	 "/session/e00594537a51dcfd2c610cdad8f89d8c/url"
[11:15:37]  DATA		{"url":"https://en.wikipedia.org/wiki/Cat#Taxonomy_and_evolution"}
```
and it hangs here indefinitely (until our test runner timesout) 

This issue is happening on the latest version of chrome (64) but does not happen on the previous version of chrome (63). 

## Link to Selenium/WebdriverIO logs

https://gist.github.com/jhoguet/a3a93d3ce92eebb3b980ce78e7dc01f5

Here is a link to the diff (https://www.diffchecker.com/rzaK4Gcu). 

## Code To Reproduce Issue

```js
const webdriverio = require('webdriverio');

webdriverio.remote({
        desiredCapabilities: { browserName: "chrome" },
        host: 'localhost',
        port: 9515,
        path: '/',
        logLevel: process.env.LOG_LEVEL || 'silent',
        coloredLogs: true
    })
    .init()
    .url('https://en.wikipedia.org/wiki/Cat')
    .url('https://en.wikipedia.org/wiki/Cat#Taxonomy_and_evolution')
    .then(() => console.log('resolved'))
    .catch(err => console.log('rejected', err))
```

Let me know if there is anything further I can do to help triage this.

**Comment by giggio** [comment]
@jhoguet this would be an issue with chromedriver itself, not with this package. This package only install chromedriver. I suggest you open an issue directly on their issue tracker.
