### ISSUE TITLE
Prevent download of chromedriver binary

### ISSUE THREAD

**Issue by ORESoftware** [giggio/node-chromedriver#145]
When running `npm install` is there a way to prevent downloading chromedriver each time?

is there a way to store the downloaded files in a central place using an env variable?

I'd like to do this:

```bash
export CHROMEDRIVER_SKIP_DOWNLOAD="yes"
npm install
```

the above would not download the chromedriver files

**Comment by ORESoftware** [comment]
Ideally if we do a controf+f in the readme for "skip" this env flag would be documented

**Comment by giggio** [comment]
We can't be sure if the version is the one you are installing at the moment, as the zip does not contain the version number. But I guess this can be fixed. I like the idea. Send a PR!

**Comment by giggio** [comment]
@ORESoftware your request was partially implemented on PR #181. You can now skip the download. We don't yet have a way to install it somewhere else. But, if you do it yourself and add it to your PATH, it will work.
Is this enough to close this issue?

**Comment by ORESoftware** [comment]
yeah that works for me thx
