### ISSUE TITLE
2.38 is released

### ISSUE THREAD

**Issue by OP-Klaus** [giggio/node-chromedriver#151]
just a note

**Comment by OP-Klaus** [comment]
PR at https://github.com/giggio/node-chromedriver/pull/152

**Comment by giggio** [comment]
Published to npm right now.

**Comment by apallithekethil** [comment]
I am having issues with my existing Selenium scripts in c# after upgrading to Chrome Driver 2.38 on Chrome v66. It doesn't seem to click on a search bar to send key data. Has anyone had this issue please?
