### ISSUE TITLE
Only Linux 64 bits supported.

### ISSUE THREAD

**Issue by karneaud** [giggio/node-chromedriver#156]
I have the following docker file

```
FROM arm64v8/node:latest

COPY ./phantomjs /usr/local/bin/phantomjs
COPY ./chromedriver-v2.0.0-linux-arm64.zip /chromedriver-v2.21-linux-arm.zip
COPY ./chromedriver /usr/local/bin/chromedriver

ENV CHROMEDRIVER_FILEPATH=/chromedriver-v2.21-linux-arm.zip
ENV PHANTOMJS_PLATFORM=linux
ENV PHANTOMJS_BITSIZE=64
ENV PHANTOMJS_ARCH=arch

RUN chmod +x /usr/local/bin/phantomjs
RUN chmod +x /usr/local/bin/chromedriver

RUN npm i -g phantomjs-prebuilt chromedriver phantomjs --unsafe-perm
```

When trying to build the image I get the following

> Only Linux 64 bits supported.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! chromedriver@2.38.3 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the chromedriver@2.38.3 install script.

What exactly does that mean? is this package fully compatible?

**Comment by giggio** [comment]
Chromedriver is not compatible, so there is nothing we can do. You can see the latest binaries here, notice only 64 is available: https://chromedriver.storage.googleapis.com/index.html?path=2.38/

**Comment by pi-jzl** [comment]
Try version 2.24
https://chromedriver.storage.googleapis.com/index.html?path=2.24/
http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux32.zip
