### ISSUE TITLE
NSP vulnerability in request package

### ISSUE THREAD

**Issue by marcato15** [giggio/node-chromedriver#160]
There's a vulnerability in `chromedriver`'s version of `request`  that has been fixed in subsequent `request` versions. 

https://nodesecurity.io/advisories/664

**Comment by giggio** [comment]
Duplicate of #144, already fixed on `2.38.1` when request was updated to `2.85.0`.
To confirm, I just ran an install, and npm reported the packages are ok.

![npm install](https://user-images.githubusercontent.com/334958/41049303-ff244bde-6986-11e8-95bb-bd2c745af221.png)

**Comment by marcato15** [comment]
It's actually a separate vulnerability than #144. `request@2.85.0` contains the `stringstream` vulnerability - https://github.com/request/request/issues/2938 - that has been since resolved.

**Comment by giggio** [comment]
Ok, reopening. Weird that npm is not showing this.

**Comment by giggio** [comment]
Just updated it, will release it with 2.39 in a moment.
