### ISSUE TITLE
`bind()` error (99) from `v2.40.0` using Selenium

### ISSUE THREAD

**Issue by hvolschenk** [giggio/node-chromedriver#163]
Hiya,

Been having an issue with `2.40.0` with Selenium inside a Docker container.
I start up selenium and it starts up `chromedriver`, but I keep getting the following rather vague error:

```
Starting selenium server... Starting ChromeDriver 2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7) on port 9515
Only local connections are allowed.
[1531234406.082][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
started - PID:  28
```

I am also not really sure where to start debugging or looking for logs etc.

Maybe someone could point me in the right direction?

**Comment by giggio** [comment]
I have no idea, this package only install ChromeDriver, you need to task to the Chromedriver devs.

**Comment by VeeTeeDev** [comment]
@hvolschenk 

Sorry to add this overhere... but did you get it to work ?
I'm struggling with the same issue and I'm wondering what it can be

**Comment by hvolschenk** [comment]
@VeeTeeDev 
I have been having this log for a while. Still have it in my logs, however everything seems to work.
I have an example repository here: https://github.com/hvolschenk/nightwatch-docker
It is slightly behind (in package versions) but it does work.

**Comment by giggio** [comment]
Please direct this conversation to the Chromedriver repo.
