### ISSUE TITLE
Starting Chromedriver fails on AWS Lambda

### ISSUE THREAD

**Issue by WinstonN** [giggio/node-chromedriver#165]
Hello 

We are trying to launch ChromeDriver in AWS Lambda, 
We use this: https://www.npmjs.com/package/chromedriver

Starting chromedriver, we get the following error:

```
Starting ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706) on port 9515
Only local connections are allowed.
[1533295707.820][SEVERE]: CreatePlatformSocket() returned an error, errno=1: Operation not permitted (1)
```

Have you seen this before? If so, did you manage to fix it?

Winst

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
