### ISSUE TITLE
Chromedriver fails to install on CentOS 7

### ISSUE THREAD

**Issue by quilicicf** [giggio/node-chromedriver#166]
Hi, 

We're trying to install chromedriver on CI on a 64 bit CentOS 7 and the installation fails with `Only linux 64 bits supported`.

Running lscpu on our machine yields:

```
$ lscpu
Architecture :        x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :            Little En
```

From install.js, we noticed that the 64-bits test is `process.arch === 'x64'` and we're wondering if chromedriver should fail for `x86_64` or not, we assume not, can you confirm/infirm?

Thanks,

**Comment by giggio** [comment]
Chromedriver is not compatible with Linux 32 bits, so there is nothing we can do. You can see the latest binaries on their site, notice only 64 bits is available: https://chromedriver.storage.googleapis.com/index.html?path=2.41/

**Comment by quilicicf** [comment]
Well, the problem is that the OS is not in 64 bits (in my case it's a docker image) while the processor is. 
It's not exactly clear in your automatic message what the issues can be, maybe you could update it?

Something like:

> ChromeDriver is only compatible with 64 bits on Linux, to understand which of the OS/processor makes the installation fail on your machine, please run the following: 

```sh
echo "OS architecture: $(uname -m)"; echo "Processor architecture: $(uname -p)"
```

> Both should show `x86_64`

**Comment by giggio** [comment]
The message is: `'Only Linux 64 bits supported.'`. I think it is good enough.

https://github.com/giggio/node-chromedriver/blob/1e97332826aced66fe1b3368e50d8b279c7b3bf9/install.js#L27

**Comment by quilicicf** [comment]
I was talking about your response here on GitHub :-)

**Comment by giggio** [comment]
Oh, ok, I will improved the answer template. Thanks for the tip.
