### ISSUE TITLE
Unable to install through npm - Unexpected end of JSON

### ISSUE THREAD

**Issue by KyleFairns** [giggio/node-chromedriver#168]
I'm attempting to install chromedriver through npm, and the error I am getting back is:

`npm ERR! Unexpected end of JSON input while parsing near '...tarball":"https://reg'`

On further inspection (through the debug log):

```
17 http fetch GET 304 https://registry.npmjs.org/chromedriver 175ms (from cache)
18 silly fetchPackageMetaData error for chromedriver@^2.40.0 Unexpected end of JSON input while parsing near '...tarball":"https://reg'
19 http fetch GET 200 https://registry.npmjs.org/chromedriver 6ms (from cache)
20 silly fetchPackageMetaData error for chromedriver@^2.40.0 Unexpected end of JSON input while parsing near '...tarball":"https://reg'
21 timing stage:rollbackFailedOptional Completed in 1ms
```

**Comment by giggio** [comment]
Isn't this a problem with Npm? Did you try later? Did it work?

**Comment by KyleFairns** [comment]
I tried upgrading my version of node, so I'm now on 10.10.0 with npm 6.4.1, and it's still giving me the same error.

**Comment by giggio** [comment]
I can't reproduce the error. Are you able to collect more information? Do you see the error in any other machines?

**Comment by KyleFairns** [comment]
I had to force it to clean the cache - something weird must have been happening in the back of npm
