### ISSUE TITLE
Currently using deprecated socks package version - must update

### ISSUE THREAD

**Issue by SylvesterAbreu** [giggio/node-chromedriver#169]
Hi all,

I did install nightwatch earlier and I got the error below where current version of socks@1.1.10 is deprecated.
The purpose of this ticket is to update the version of socks to latest which at the time of reporting this issue is 2.2.1. The latest version can be found [here](https://www.npmjs.com/package/socks).

`$ npm install -g nightwatch
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0`

**Comment by giggio** [comment]
I think you posted to the wrong repo, we don't use either of those packages.
