### ISSUE TITLE
chromedriver is not supported in arm platforms

### ISSUE THREAD

**Issue by pruthvireddy1991** [giggio/node-chromedriver#172]
I am running this package in arm64 platform.
uname -a
Linux e7fac9d4ba1c 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
node -v
v10.9.0

Getting below driver while running npm install in arm64 platform:
npm install

> chromedriver@2.42.0 install /node-chromedriver
> node install.js

Only Linux 64 bits supported.

Please suggest me a solution on solving this issue.
Thanks in advance.

**Comment by giggio** [comment]
ChromeDriver is only compatible with 64 bits on Linux, to understand which of the OS/processor makes the installation fail on your machine, please run the following:

````bash
echo "OS architecture: $(uname -m)"; echo "Processor architecture: $(uname -p)"
````

Both should show `x86_64`.

You can see the latest binaries on their site, notice only 64 bits is available: https://chromedriver.storage.googleapis.com/index.html?path=2.41/
