### ISSUE TITLE
Intermittently conntection issues on windows bases systems

### ISSUE THREAD

**Issue by HaNdTriX** [giggio/node-chromedriver#174]
We are having issues with chromedriver on windows based systems.
We are running the same setup on linux based systems and it works fine there.
Any help will be appreciated. 

## System infos:

chromedriver version: `2.42.0`
OS Version: `win2016` applies to other windows based systems as well
Node Versions: `^8.12.0` & `^10.10.0`

## Error Message

```log
Starting ChromeDriver 2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5) on port 9515
...............................
.......after some time.........
...............................
[1539302393.757][WARNING]: Timed out connecting to Chrome, retrying...
```

## Example log

https://dev.azure.com/nextjs/next.js/_build/results?buildId=267&view=logs

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
