### ISSUE TITLE
Passing empty string in args of chromeoptions is causing the browser to load all the possible args in each tab

### ISSUE THREAD

**Issue by spnraju** [giggio/node-chromedriver#178]
I am using nightwatchjs and I am passing the args as **args: ['headless', 'disable-gpu']** and this works great. 

But when I pass **args: ['', 'disable-gpu']** in chromeoptions, it is trying to load all the possible args in chrome tabs. 

This can be a low priority issue. but wanted to let you know.

This was happening in Windows 10 and chromedriver 2.40.0

**Comment by giggio** [comment]
This is a Webdriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Webdriver team on their [issue tracker](https://github.com/SeleniumHQ/selenium/issues).
