### ISSUE TITLE
Use global chromedriver bin

### ISSUE THREAD

**Issue by aberonni** [giggio/node-chromedriver#180]
I'm thinking of opening a PR for this, but before doing so I would like feedback on whether it would be accepted.

I would like the module to use a global installation of chromedriver, so I don't need the module to download chromedriver nor check versions - just use the global installation. This way I can use the JS module simply as an interface to manage the global installation.

I would like to propose that `CHROMEDRIVER_USE_GLOBAL=true` would skip downloading the chromedriver, and use the global chromedriver installation. So basically `exports.path` in https://github.com/giggio/node-chromedriver/blob/master/lib/chromedriver.js#L3 would simply be `'chromedriver'`

@giggio what do you think?

**Comment by giggio** [comment]
I think that those are two different but connected things.

If you don't want to download the binary, I prefer to be explicit about it and call it `CHROMEDRIVER_SKIP_DOWNLOAD`.

Then, when running, we could check if the binary exists. If not, we then export simply `chromedriver` (or `chromedriver.exe` for Windows).

Additionally, you could add another argument to the `start` method, this could be `useSystemChromedriver`.

**Comment by aberonni** [comment]
I gave it a shot in https://github.com/giggio/node-chromedriver/pull/181, let me know what you think
