### ISSUE TITLE
Error when trying to download chromedriver binary

### ISSUE THREAD

**Issue by doberkofler** [giggio/node-chromedriver#185]
I'm not sure if this error is related to node-chromedriver or the binary itself but when downloading it manually the binary seems to work as expected:

```
ChromeDriver binary exists. Validating...
Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/LATEST/chromedriver_win32.zip
Saving to file: C:\temp\chromedriver\chromedriver_win32.zip
Received 0K total.
Extracting zip contents
ChromeDriver installation failed Error extracting archive: Error: end of central directory record signature not found
```

**Comment by giggio** [comment]
I just tested version `2.43.2` and it installed fine. It is strange that it posted `Received 0K total`. Here are my logs:

```
$ npm i -S chromedriver

> chromedriver@2.43.3 install C:\p\rabiscos\testechro\node_modules\chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.43/chromedriver_win32.zip
Saving to file: C:\Users\<redacted>\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Received 782K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3529K total.
Extracting zip contents
Copying to target path C:\proj\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at C:\proj\node_modules\chromedriver\lib\chromedriver\chromedriver.exe

+ chromedriver@2.43.3
updated 1 package and audited 137 packages in 3.782s
found 0 vulnerabilities
```

Can you try to manually write to `C:\temp\chromedriver\chromedriver_win32.zip`? Have you tried on another machine? Does it work?
You can try setting your environment variable `TEMP`, and seeing if it works.

**Comment by doberkofler** [comment]
- I just tried again and it still does not work
- I have been using this packages for several years and it just stopped working now
- I have tried on several workstations and it still fails on all of them
- I have tried to download, copy and extract the driver in the temp directory and this works
- The `C:\temp\chromedriver\chromedriver_win32.zip` has a size of 1k and the file contains the following:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/LATEST/chromedriver_win32.zip</Details></Error>
```

**Comment by giggio** [comment]
There was a change on `2.43.2` that may be causing this issue. Can you try `2.43.1` and see if it works?

**Comment by doberkofler** [comment]
Sorry I did not try this already. Yes, 2.43.1 is working!

**Comment by giggio** [comment]
Ok, there was a release `2.43.3`. Can you try that version?

**Comment by doberkofler** [comment]
Unfortunately the error persists in 2.43.3

**Comment by giggio** [comment]
Is the log the same?

**Comment by doberkofler** [comment]
yes:

```
> chromedriver@2.43.3 install D:\MyDev\ljs_app\branches\trunk_ts\periscope\build\node_modules\chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/LATEST/chromedriver_win32.zip
Saving to file: C:\temp\chromedriver\chromedriver_win32.zip
Received 0K total.
Extracting zip contents
ChromeDriver installation failed Error extracting archive: Error: end of central directory record signature not found
```

**Comment by doberkofler** [comment]
Can you reproduce the problem yourself or can I somehow help tracing the problem ?

**Comment by giggio** [comment]
What node and npm versions are you using?

**Comment by giggio** [comment]
Ok, I was able to reproduce. You are using the `LATEST` config. That shows the error.

**Comment by giggio** [comment]
@doberkofler Fixed on `2.43.4`. Would you please test it? If it is ok I'll update it to 2.44, which seems to just be out.

**Comment by doberkofler** [comment]
It is working now. Thank you!

**Comment by gayanSandamal** [comment]
I had the same issue and tried the all the fixes but didn't work.
Then I updated the .npmrc with by adding this line,
`chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver`
 file which is located at "C:\Program Files\nodejs\node_modules\npm\npmrc"

and ran `npm update`

**Comment by rojobuffalo** [comment]
I have this same issue now with v2.46

**Comment by giggio** [comment]
It is probably a different problem, by looking at the logs. You seem to have a connection problem.
