### ISSUE TITLE
Replace `request` lib?

### ISSUE THREAD

**Issue by cktang88** [giggio/node-chromedriver#189]
Request is really bloated, and since it seems to only be used here to make a simple GET request, we can easily replace it with something lighter like `got` or `axios`. See https://bundlephobia.com/result?p=request@2.88.0

**Comment by ksathyanm** [comment]
As of Feb 11th 2020, request is fully deprecated.

https://github.com/request/request/issues/3142#issuecomment-584745385

**Comment by giggio** [comment]
Yes, this makes sense to update, now. I'll check out some options.

**Comment by giggio** [comment]
Ok, I'm almost done moving to Axios. Got would be hard to use because of proxies and CAs, and Bent is too simple, wouldn't support most of what this library is doing.

**Comment by giggio** [comment]
Published just now as `80.0.1`. Please test if it works, as I changed a lot of the code around.

**Comment by AbdelAbdelAli** [comment]
hi guys 
I installed angular 9 cli, my node.js is on latest version. While I try to create a new angular project im getting the following error.

/ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404 'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\user\AppData\Roaming\npm-cache_logs\2020-02-12T04_52_40_200Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by giggio** [comment]
@AbdelAbdelAli How is this related to `node-chromedriver`? Can you give us more info? We just removed request from the dependencies.
