### ISSUE TITLE
failed to wait for extension background page to load

### ISSUE THREAD

**Issue by Stngle** [giggio/node-chromedriver#194]
Hi,
     i use chrome driver in headless mode, there is something wrong in my case as follows:

`unknown error: failed to wait for extension background page to load: chrome-extension://donpflcacamajpbnhjxxxxx/_generated_background_page.html from timeout`

Driver info: chromedriver=2.46.628402, platform=windows NT 6.1.7601 sp1 x86_64
Browser Version: 72.0.3626.121

The request arguments:

`{
                args: ['--enable-automation', '--disable-bundled-ppapi-flash'],
                prefs: {
                    'plugins.plugins_disabled': ['Adobe Flash Player']
                },
                extensions: [extContent]
 }`

**Comment by Stngle** [comment]
```
var crxPath = path.resolve(__dirname, '../tool/uirecorder.crx');
var extContent = fs.readFileSync(crxPath).toString('base64');
```

Add it, i read the .crx file use base64.

**Comment by Stngle** [comment]
DevTools listening on ws://127.0.0.1:21490/devtools/browser/8f7ecee4-1d97-49e7-a
57e-43e79973be6d

DevTools listening on ws://127.0.0.1:21502/devtools/browser/389337b2-5467-430b-8
967-855a147ecc57
Chrome打开失败！
unknown error: failed to wait for extension background page to load: chrome-exte
nsion://donpflclacamajgbnhgjgkkapnlfahlj/_generated_background_page.html
from timeout
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361
e1),platform=Windows NT 6.1.7601 SP1 x86_64)
Chrome打开失败！
{ Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', sysca
ll: 'read' }

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
