### ISSUE TITLE
Starting chromedriver just hangs

### ISSUE THREAD

**Issue by ekosynth** [giggio/node-chromedriver#202]
Today I've tried to start Chromedriver (Through Nightwatch and individually) and it just hangs:

```
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```

Any idea what could be causing this?

**Comment by giggio** [comment]
I believe this is normal behavior.
Anyway, this is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
