### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by krazyjakee** [giggio/node-chromedriver#204]
Hi all, I'm using the latest chrome (74.0.3729.159) on ubuntu 18 in docker.

Chromedriver 74.0.0 throws this error:

```
Error: ChromeDriver process exited with code: 2
   /usr/src/app/node_modules/chromedriver/lib/chromedriver/chromedriver: 1: /usr/src/app/node_modules/chromedriver/lib/chromedriver/chromedriver: Syntax error: word unexpected (expecting ")")
  
       at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
 /usr/src/app/node_modules/chromedriver/lib/chromedriver/chromedriver: 1: /usr/src/app/node_modules/chromedriver/lib/chromedriver/chromedriver: Syntax error: word unexpected (expecting ")")
```

What could cause this? Is it a known issue?

**Comment by giggio** [comment]
Are you on a supported Node.js version? We support all LTS versions, at this moment 8 and greater.

**Comment by krazyjakee** [comment]
@giggio thanks for the response.
I am using node 12

**Comment by krazyjakee** [comment]
Note that it works on osx running node 12

**Comment by krazyjakee** [comment]
Solved!

The error was due to the request failing as the site was not online.
For example, I asked chrome to open a url but it failed (not online) and so this useless error was thrown.
