### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by ccorcos** [giggio/node-chromedriver#205]
Hey there, I know that this issue might not be in this library, but I cannot figure it out and perhaps you can point me in the right direction.

I have chrome and chrome driver installed at the same versions:

```
chet@18ade839c3f5:~/repo$ /usr/bin/google-chrome --version
Google Chrome 73.0.3683.86
chet@18ade839c3f5:~/repo$ ./node_modules/.bin/chromedriver --version
ChromeDriver 73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017)
```

I start chrome driver with a few options that people on the internet say _should_ fix my problem. I've tried with and without all combinations of these options:

```ts
await chromedriver.start(
	["--headless", "--no-sandbox", "--disable-dev-shm-usage"],
	true
)
```

Chromedriver seems to start without issue:

```
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1558656497.018][SEVERE]: bind() failed: Cannot assign requested address (99)
```

I connect with the selenium webdriver referenced in your README.

```
import {	Builder } from "selenium-webdriver"
const driver = new Builder().forBrowser("chrome").build()
```

And at some point I end up getting this error.

```
     WebDriverError: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Linux 4.9.125-linuxkit x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:585:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:533:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

I can't seem to figure it out. Any ideas what's going on here? 

Additional information: I'm running this inside a docker container as a non-root user.

Thanks

**Comment by giggio** [comment]
This is most likely some restriction coming from Docker.

This is how I used to run Chrome on a container:
https://github.com/giggio/docker-chrome/blob/master/Dockerfile

[Note](https://github.com/giggio/docker-chrome#running) that I used `--cap-add=SYS_ADMIN` to run it, you could try that. But from what I read recently, your adding `--no-sandbox` should allow you to run without that cap.

````bash
docker run -ti -p 9222:9222 --cap-add=SYS_ADMIN giggio/chrome
````

I also ran it with `--disable-gpu`. That could help too.

I'm closing this issue because this is surely not a problem with the package. But feel free to comment.

**Comment by ccorcos** [comment]
Hmm. So you're running chrome and then running chrome driver?

https://github.com/giggio/docker-chrome/blob/master/Dockerfile#L9

**Comment by ccorcos** [comment]
I figured `chromedriver.start()` was running chrome and passing those arguments through...

**Comment by ccorcos** [comment]
Hmm. I can run google chrome just fine with these options:

```
$ google-chrome --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"

DevTools listening on ws://0.0.0.0:9222/devtools/browser/b88661d7-1c50-49ab-b535-17d6d0a3fade
```
