### ISSUE TITLE
Release ChromeDriver v75

### ISSUE THREAD

**Issue by jahed** [giggio/node-chromedriver#207]
ChromeDriver v75 has been out for a month and v74 is having issues with the latest Chromium release. Can someone make a release for it?

Thanks.

**Comment by giggio** [comment]
75 is still beta. You can use versioning if you need it: https://github.com/giggio/node-chromedriver#versioning
This is also a duplicate of #201.
I'll close the issue, feel free to reopen when it is really released.

**Comment by jahed** [comment]
Ah, that explains why "LATEST" didn't work. I'll just stick to v74 then.

Apologies for the duplicate, I didn't search PRs.

Thanks again.
