### ISSUE TITLE
Does not run install.js hence no chromedriver.exe installed on windows

### ISSUE THREAD

**Issue by EllinMengmeng** [giggio/node-chromedriver#210]
Hi, We used yarn to install the dependencies for our projects(which also includes node-chromedriver). We used yarn 1.16.0 and node 10.14.0 for our environment. The issue is: sometimes seems thatthe install.js is not executed during our yarn step, so the chromedriver.exe is downloaded(since we saw no console log from the yarn log). 
What could cause this? Is it a known issue? Thank you in advanced

**Comment by giggio** [comment]
I have never seen this with npm, it always runs. You have no logs?

**Comment by EllinMengmeng** [comment]
Yes, we have log for our yarn install step. In the successful case, we can see the log like this:
07:18:27 [Windows] verbose 42.26 Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
07:18:27 [Windows] Downloading from file:  https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_win32.zip
07:18:27 [Windows] Saving to file: C:\Users\Administrator\AppData\Local\Temp\74.0.3729.6\chromedriver\chromedriver_win32.zip
07:18:27 [Windows] Received 781K...
07:18:27 [Windows] Received 1568K...
07:18:27 [Windows] Received 2352K...
07:18:27 [Windows] Received 3136K...
07:18:27 [Windows] Received 3920K...
07:18:27 [Windows] Received 4513K total.
07:18:27 [Windows] Extracting zip contents
07:18:27 [Windows] Copying to target path C:\jenkins\workspace\te-\node_modules\chromedriver\lib\chromedriver
07:18:27 [Windows] Done. ChromeDriver binary available at C:\jenkins\workspace\te-\node_modules\chromedriver\lib\chromedriver.

However, in the failure case, we can see nothing that is console.log from the install.js. And this only happened from the last month. So it seems the install.js does not even run. Do you have some ideas? Thx

**Comment by EllinMengmeng** [comment]
We found out that if we send too many request to google, google will first slow down the request and then if there are still lots of request from the same Ip, it will even block. I think this is the reason why we cannot have the binary downloaded. But it is strange since if the download step failed, the log "Current existing ChromeDriver binary is unavailable, proceding with download and extraction." should still be seen in the yarn log.

**Comment by giggio** [comment]
All of these lines are logs from `install.js`:

````
07:18:27 [Windows] Saving to file: C:\Users\Administrator\AppData\Local\Temp\74.0.3729.6\chromedriver\chromedriver_win32.zip
07:18:27 [Windows] Received 781K...
07:18:27 [Windows] Received 1568K...
07:18:27 [Windows] Received 2352K...
07:18:27 [Windows] Received 3136K...
07:18:27 [Windows] Received 3920K...
07:18:27 [Windows] Received 4513K total.
07:18:27 [Windows] Extracting zip contents
07:18:27 [Windows] Copying to target path C:\jenkins\workspace\te-\node_modules\chromedriver\lib\chromedriver
07:18:27 [Windows] Done. ChromeDriver binary available at C:\jenkins\workspace\te-\node_modules\chromedriver\lib\chromedriver.
````

I can't see a reason for the binary not showing up. Does it only happen on one machine?

**Comment by giggio** [comment]
Oh, I see, you see these lines on another situation.
I can't be sure, but this seems to be a problem with yarn. I'll check in my local machine and see if it also shows up.

**Comment by giggio** [comment]
Ok, I could reproduce, this is a problem with Yarn. If you don't have a `package.json` it won't save anything to `node_modules`.
My recommendation is: just use npm.
Or, if you really want to use yarn, add a `package.json` to the directory. A `yarn init -y` should do it.
