### ISSUE TITLE
On Windows, chromedriver_filepath to exe (rather than zip) results in ENOENT error at runtime

### ISSUE THREAD

**Issue by dbjorge** [giggio/node-chromedriver#212]
On a Windows system, if you pass the `chromedriver_filepath` config pointing directly to `chromedriver.exe` (as opposed to a zip file), the file gets copied to `tmpPath` as `chromedriver` rather than `chromedriver.exe` like it would have it in the zip path. Later, when it looks for the platform-appropriate binary to run, it can't find it (because it's looking for `chromedriver.exe`) and errors out with an ENOENT message.

I think the fix would be in line 261 in `extractDownload()`. I think you'd want to replace the current line,

```
fs.copyFileSync(downloadedFile, path.resolve(tmpPath, 'chromedriver'));
```

...with...

```
fs.copyFileSync(downloadedFile, chromedriverBinaryFilePath);
```

**Comment by giggio** [comment]
Bug confirmed.
