### ISSUE TITLE
A dot before domain field in cookies is not returned through chrome driver

### ISSUE THREAD

**Issue by spnraju** [giggio/node-chromedriver#214]
Hi there, 
Thank you so much this repo.

we are testing cookies as part of unit testing in [W3C WebDriver](https://github.com/w3c-webdriver/w3c-webdriver). As part of that, we are adding and retrieving a cookie. We are adding a cookie with domain name as '.localhost' and expecting same to be retrieved. But starting chromedriver v75, it is retrieved as 'localhost' without the dot. This is working well in other browsers than in other browsers as well as with lower version of chromedriver.

Link to tests : https://github.com/w3c-webdriver/w3c-webdriver/blob/dependabot/npm_and_yarn/packages/w3c-webdriver/chromedriver-75.0.1/packages/w3c-webdriver/test/16-cookies.test.ts#L5

Link to test logs: https://dev.azure.com/w3c-webdriver/w3c-webdriver/_build/results?buildId=470&view=logs&jobId=3a56a3f7-2811-5bf6-b1aa-95eb2b39c372&taskId=0c13f5ed-dfde-5c67-ad45-787d21e1b9fc&lineStart=487&lineEnd=488&colStart=1&colEnd=1

Pull request to upgrade chromedriver in our repo: https://github.com/w3c-webdriver/w3c-webdriver/pull/228

Kindly let me know if you need more details.

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
