### ISSUE TITLE
ChromeDriver 75.0.3770.8 (node-chromedriver@75.0.1) has a bug  - upgrade is required to 75.0.3770.90

### ISSUE THREAD

**Issue by vlad-vinogradov** [giggio/node-chromedriver#215]
ChromeDriver 75.0.3770.8 has a bug  - new release is required with ChromeDriver 75.0.3770.90.
  
See:
* [chromedriver issue 2943](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2943#c9)  
* [ChromeDriver - Version Selection](http://chromedriver.chromium.org/downloads/version-selection)

**Comment by giggio** [comment]
Thanks for the heads up.
Published as `75.1.0`.
