### ISSUE TITLE
node-chromedriver unhappy with snap and symbolic link

### ISSUE THREAD

**Issue by eric-burel** [giggio/node-chromedriver#216]
Hi,
I am trying to force the use of the locally installed chrome driver on Ubuntu 18.04, given that I use Chromium and it is installed using snap.

When I run this command:

`npm install chromedriver --chromedriver_filepath="/snap/bin/chromium.chromedriver`

`node_modules/chromedriver/bin/chromedriver` is not Chrome driver, but the  `snap` binary.

This makes sense because Snaps are actually symbolic links to `/usr/bin/snap`. I suppose snap will analyse the path when running an app to detect which snap to run, and this behaviour is somehow broken when passing down the command to another tool like Chrome Driver.

I can't give much other insights as I am not knowledgeable at all on these subject, but basically I think the way `chromedriver_filepath` is handled could be improved somehow to solve this. 

Maybe the command should be kept in memory instead of copying the file when it's a symbolic link or a snap?

**Comment by giggio** [comment]
If you already have Chromedriver installed you don't need this module. This module exists to install it. The little JS we offer is just to configure the file path and start it. I suggest that if you need it, just grab it from here.

**Comment by eric-burel** [comment]
Just to give more cotnext (for our fellow googlers) I am using a 3rd party module to set up the tests, `meteortesting:mocha`, so I don't have much control on the actual setup, just on how node-chromedriver is installed. 
But anyway there are a lot of workarounds, like manually downloading the driver .zip and linking the file directly instead of using the snap.
