### ISSUE TITLE
execute `npm install`,the process won't finish

### ISSUE THREAD

**Issue by SongJuXin** [giggio/node-chromedriver#218]
When i executed `npm install` in my project.The process stop at `Saving to file:`.
<img width="1244" alt="exit" src="https://user-images.githubusercontent.com/20874344/62268698-3d9d6d00-b463-11e9-834d-9e6cf0c432eb.png">
Actually the process has been finished  because once i press `ctrl+c(exit process)`,the success info will be  occur.

environment:macOS 10.14.4,webstorm terminal,npmV6.4.1

**Comment by giggio** [comment]
I don't have a mac, and the issue is not being repro on any of the build agents. Are you able to debug the issue in a way that can direct us to the problem?
Can you download the file from this location? Can you do it using node? How about debug the install.js file?

**Comment by SongJuXin** [comment]
Thank you for your reply.My English is bad.
I find the casue of previous problem.It's network!
To begin with,the problem is't always occur.

I try `node install.js` and `ping https://chromedriver.storage.googleapis.com(the download url of chrome driver ) ` at the same time.Then,a magical scene appeared.The ping result show me that the network is oddly.In other words,the download process will stay when the network is bad.
<img width="1372" alt="stayed1" src="https://user-images.githubusercontent.com/20874344/62591627-cce2ce80-b902-11e9-9374-246fb0a3b366.png">

Now,the case has been find.

**Comment by giggio** [comment]
Ok, I am glad you solved it.
