### ISSUE TITLE
chromeOptions being ignored

### ISSUE THREAD

**Issue by Jayce53** [giggio/node-chromedriver#219]
Since updating to version 76 the chromeOptions seem to be ignored.  e.g. the following code ignores the "--headless" flag and starts a headed browser (chromedriver v 2.44.1 works OK - 2.44.1 is most recent version that will work with Chrome 76)

```
const webdriver = require('selenium-webdriver');
require('chromedriver');

const chromeOptions = {
    args: ["--headless", "--disable-gpu", "--window-size=1900x1200"]
};

const capabilities = {
    browserName  : 'chrome',
    platform     : 'WIN10',
    version      : 'latest',
    idletimeout  : 30,
    chromeOptions: chromeOptions
};


const driver = new webdriver.Builder()
    .forBrowser('chrome')
    .withCapabilities(capabilities)
    .build();

driver
    .then(function () {
        console.log('done');
    });
```

Using the following package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "Test chromedriver",
  "private": true,
  "author": "Jayce53",
  "license": "ISC",
  "devDependencies": {
    "chromedriver": "76",
    "selenium-webdriver": "4.0.0-alpha.4"
  }
}
```

**Comment by fr-ser** [comment]
I had the same problem. Then I upgraded to selenium alpha.4 and the newest 76 version and it worked again.

This is how my package.json looks

```
    "chromedriver": "^76.0.0",
    "selenium-webdriver": "^4.0.0-alpha.4",
```

**Comment by Jayce53** [comment]
They're exactly the versions I am using and I still have the problem.  In fact it only occurred after updating to chromedriver 76.0.0

**Comment by fr-ser** [comment]
Same thing for me (I updated from 2.sth to 76). I was thinking, that maybe the caret (^) was making a difference as I could have a newer version than 76.0.0

**Comment by patricksmms** [comment]
I'm also experiencing the same. Updating `chrome-driver` and `selenium-webdriver` didn't help.

**Comment by alicanerdogan** [comment]
Adding an additional parameter to `chromeOptions`  named `w3c` with value `false` worked for me.

```js
const webdriver = require('selenium-webdriver');
require('chromedriver');

const chromeOptions = {
    w3c: false,
    args: ["--headless", "--disable-gpu", "--window-size=1900x1200"]
};

const capabilities = {
    browserName  : 'chrome',
    platform     : 'WIN10',
    version      : 'latest',
    idletimeout  : 30,
    chromeOptions: chromeOptions
};


const driver = new webdriver.Builder()
    .forBrowser('chrome')
    .withCapabilities(capabilities)
    .build();

driver
    .then(function () {
        console.log('done');
    });
```

source: https://stackoverflow.com/questions/56111529/cannot-call-non-w3c-standard-command-while-in-w3c-mode-seleniumwebdrivererr#answer-56456696

**Comment by patricksmms** [comment]
@alicanerdogan, unfortunately this also didn't help in my case.

**Comment by giggio** [comment]
This is a Chromedriver or a webdriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
