### ISSUE TITLE
Chrome version detection

### ISSUE THREAD

**Issue by senovsky** [giggio/node-chromedriver#220]
Hi
Thanks for the good work, really appreciate it.
One thing that would make it even better would be an option to download the version of chromedriver that corresponds to the version of Chrome installed. It would solve the problem when chromedriver gets updated to the latest version, but Chrome hasn't updated itself yet.
(Unfortunately, latest chromedriver isn't backwards compatible with previous versions of Chrome.)
Thanks in advance if you're gonna implement this, it would solve a lot of CI/CD headaches.

**Comment by giggio** [comment]
This seems quite complicated, as I don't even know where this information is published, if it is published. Would you know?

**Comment by senovsky** [comment]
This works for me on Windows:
`reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version`
https://stackoverflow.com/questions/50880917/how-to-get-chrome-version-using-command-prompt-in-windows

**Comment by ksathyanm** [comment]
@giggio @senovsky The official doc and the steps are [here](https://chromedriver.chromium.org/downloads/version-selection). I had the same CI/CD problem at work recently, so as per doc, I built [find-chrome-version](https://www.npmjs.com/package/find-chrome-version) and hit `${cdnUrl}/LATEST_RELEASE_${chrome-version-without-patch}` to get the compatible chromedriver version before installing node-chromedriver.

Maybe I can open a PR using [find-chrome-version](https://www.npmjs.com/package/find-chrome-version) package. Let me know if there is an alternative approach to detect the installed chrome version. I'm open to suggestions.

**Comment by senovsky** [comment]
@ksathyanm Sounds great :-) I haven't found anything better, your find-chrome-version package looks really good. Would you be able to create the said PR?

**Comment by G-Ray** [comment]
from https://chromedriver.chromium.org/downloads/version-selection
> Please don't rely on the LATEST_RELEASE file without a version suffix. It exists for backward compatibility only, and will be removed in the near future.

**Comment by senovsky** [comment]
> from https://chromedriver.chromium.org/downloads/version-selection
> 
> > Please don't rely on the LATEST_RELEASE file without a version suffix. It exists for backward compatibility only, and will be removed in the near future.

I've seen that one as well, but it doesn't apply to @ksathyanm's solution, right? Since he's using the LATEST_RELEASE file _with_ a version suffix.

**Comment by ksathyanm** [comment]
@senovsky Sure! I will create the PR. @G-Ray I used the `LATEST_RELEASE_X.X.X` one.

**Comment by giggio** [comment]
Ok, so I guess that after they aligned Chrome and Chromedriver versions it all got easier, now.
What you should do, then, is to add an option to detect the chromedriver version. It should be incompatible with the other options that specify version, such as `chromedriver_version` or `chromedriver_filepath`.

**Comment by jogonzal** [comment]
Would be great to see this one merged, it would allow us to simplify some of the steps in the CI :)

**Comment by benjamingr** [comment]
We released a package for this https://github.com/testimio/chrome-version

**Comment by benjamingr** [comment]
Hey, we have released a package for detecting the chrome version at  https://github.com/testimio/chrome-version - we intend to support this for the foreseeable future

**Comment by giggio** [comment]
@benjamingr I have asked @ksathyanm to evaluate your library on #222.

**Comment by giggio** [comment]
Closed on 67253e1 from #222, and partially from #246. Published as 79.0.2
