### ISSUE TITLE
Failed to install chromedriver on Windows 10

### ISSUE THREAD

**Issue by clerg0** [giggio/node-chromedriver#223]
hi, 
I can't install chrome driver and i don't understand why... Could you help me?
```
npm i chromedriver

> chromedriver@2.46.0 install D:\Square\git\artemis\artemis-target\artemis-app\client\node_modules\@vue\cli-plugin-e2e-nightwatch\node_modules\chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip
Saving to file: C:\Users\DCLERG~1\AppData\Local\Temp\2.46\chromedriver\chromedriver_win32.zip
ChromeDriver installation failed Error with http(s) request: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128 3128:80
npm WARN vue-loader@15.7.0 requires a peer of css-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.46.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.46.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dclergeaud\AppData\Roaming\npm-cache\_logs\2019-08-21T09_31_11_477Z-debug.log
PS D:\Square\git\artemis\artemis-target\artemis-app\client>
```

i attached the logs to this issue.
[2019-08-21T09_31_11_477Z-debug.log](https://github.com/giggio/node-chromedriver/files/3524619/2019-08-21T09_31_11_477Z-debug.log)

thx a lot

**Comment by clerg0** [comment]
Ok, i tried to install it manually by copying the folder content, i got the same error. It seems that the "node install.js" doesn't work.

**Comment by 382303784** [comment]
> It seems that you cannot download the file:
> 
> `Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128 3128:80`
> 
> Are you able to download https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip ?

Yes, I have encountered the same problem and the download failed.

**Comment by clerg0** [comment]
I can download it manually but via the command "node install.js" it fails. 
Maybe  i can finish the installation manually ?

**Comment by 382303784** [comment]
> I can download it manually but via the command "node install.js" it fails.
> Maybe i can finish the installation manually ?

me too

**Comment by giggio** [comment]
@clerg0 I can't repro the problem, I'm on Windows now and it works. Would you be able to debug `install.js` so we can better understand the problem?

**Comment by gy134340** [comment]
sorry, fixed, `https://chromedriver.storage.googleapis.com` isn't work from my side, I have to use 
`npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver`

**Comment by giggio** [comment]
I'm closing it, as we can't repro. If repro steps are posted we can investigate further.
