### ISSUE TITLE
version and location of chromedriver in node-chromedriver 2.46

### ISSUE THREAD

**Issue by luisapace** [giggio/node-chromedriver#226]
Hi, my team would use node-chromedriver 2.46 and to approve that I've to verify that all its licenses are acceptable.

Now I've seen that node-chromedriver 2.46 contains the binary code of the chromedriver, so I have to analyze also chromedriver code (and its license). 

So my question is: 
what is the version of the chromedriver included and where I can download its source code from?

Thanks for your help on this.

**Comment by giggio** [comment]
No, this project does publish the binary. It downloads it from the Chromedriver site. See `install.js` to understand how it does that.
