### ISSUE TITLE
update chromedriver to 77.0.3865.40

### ISSUE THREAD

**Issue by army8735** [giggio/node-chromedriver#228]
https://chromedriver.chromium.org/downloads

**Comment by rsshilli** [comment]
Yeah, there's no chromedriver 77.0.0 in NPM! https://www.npmjs.com/package/chromedriver

**Comment by ashubham** [comment]
Facing the same problem.

**Comment by js-kyle** [comment]
@giggio What would your stance be on adding another maintainer to this project? It is quite heavily depended on, it would be useful to get PR's merged and published with new versions faster that relying on you to do it. It could probably be automated too

**Comment by giggio** [comment]
I just published the new version with #227. 

If this update could be automated somehow it would be really nice. Just send a PR.

**Comment by anildani** [comment]
I am getting following error - Even after updating to v77.

Any idea the reason behind this error.
------------
Error retrieving a new session from the selenium server

{ state: 'session not created',

  sessionId: null,

  hCode: 518652395,

  value: 

   { additionalInformation: '\nDriver info: org.openqa.selenium.chrome.ChromeDriver',

     localizedMessage: 'session not created: This version of ChromeDriver only supports Chrome version 77\n  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Linux 4.4.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 1.17 seconds\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: host: \'localhost\', ip: \'127.0.0.1\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.4.0-101-generic\', java.version: \'1.8.0_151\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver',

     supportUrl: null,

     systemInformation: 'System info: host: \'localhost\', ip: \'127.0.0.1\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.4.0-101-generic\', java.version: \'1.8.0_151\'',

     cause: null,

     suppressed: [ [length]: 0 ],

     message: 'session not created: This version of ChromeDriver only supports Chrome version 77\n  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Linux 4.4.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 1.17 seconds\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: host: \'localhost\', ip: \'127.0.0.1\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.4.0-101-generic\', java.version: \'1.8.0_151\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver',

     hCode: 77951691,

     class: 'org.openqa.selenium.SessionNotCreatedException',

     buildInformation: 

      { buildRevision: 'a36b8b1',

        buildTime: '2016-06-30 17:37:03',

        releaseLabel: '2.53.1',

        hCode: 1730491641,

        class: 'org.openqa.selenium.internal.BuildInfo' },

     screen: null },

  class: 'org.openqa.selenium.remote.Response',

  status: 33 }
------------

**Comment by giggio** [comment]
Your Chrome seems to be the wrong version. This is not a problem with this package.
