### ISSUE TITLE
license of chromedriver ??

### ISSUE THREAD

**Issue by luisapace** [giggio/node-chromedriver#233]
Hi, as I told in the issue https://github.com/giggio/node-chromedriver/issues/226
my team would use node-chromedriver 2.46 and to approve that I've to verify that all its licenses are acceptable, including those of embedded/grabbed binaries.

I've followed what you said in that issue but unfortunately I was not able to find any location from where to download the source code of chromedriver, nor any information of its license type (GPL? Apache? others?).

May I kindly ask if you can help to reach/obtain that info? 

Thanks a lot for any help or suggestion.

**Comment by giggio** [comment]
This project is not the chromedriver project, it is only the npm package. For the chromedriver project you have to go to https://chromedriver.chromium.org/

From my understanding, the Chromedriver project is under the Chromium project. See source at:
https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/test/chromedriver/
License seems to be at:
https://chromium.googlesource.com/chromium/src/+/refs/heads/master/LICENSE

But please check this information, as I am not a lawyer.

**Comment by luisapace** [comment]
@giggio thanks a lot for your quick answer, this has been really helpful!
