### ISSUE TITLE
What to do about the day between chrome release and ChromeDriver release?

### ISSUE THREAD

**Issue by benjamingr** [giggio/node-chromedriver#237]
So, recent version of ChromeDriver only support a single version of Chrome - this means whenever Chrome updates and until you release this library (thank you a ton by the way) this library is broken.

Given Chrome releases once every 8 weeks and the releases are fairly predictable ([here](https://www.chromestatus.com/features/schedule)) it would be really great if there was a workaround for this. 

I realise I can work around it by overriding the `release` string - and that this library is "blessed" by design but a "blessed" (heh) workaround for this would still be super helpful as currently our code breaks every 8 weeks as users upgrade.

Some ideas: 

 - Publishing a beta version of this package with the beta version of Chrome
 - Publishing a version of a second unblessed chromedriver-unblessed package that tracks the chromedriver releases.
 - Anything else?

**Comment by giggio** [comment]
I suppose there might be something we can automate with Github Actions, I just haven't got around to learn it yet.
And you can always set the version:

https://github.com/giggio/node-chromedriver#versioning

**Comment by giggio** [comment]
With #222 and #246 integrated (see also README.md) this has become easier.

You can try to set the version to `LATEST_80` for example, and you will download the latest beta.

Or you can use a flag to detect your Chrome version.

@benjamingr please see if this solves your use case.

**Comment by benjamingr** [comment]
This is better - yes. Although I figured our ChromeDriver has a flag to bypass version detection and we might want to pass that by default.
