### ISSUE TITLE
Installing via yarn: Error: Target directory is expected to be absolute

### ISSUE THREAD

**Issue by CSomerville** [giggio/node-chromedriver#238]
Hello, many thanks for maintaining this package.
`yarn add chromedriver@78.0.0` works, but `yarn add chromedriver@78.0.1` fails:

```
error /Users/colby.somerville/projects/dibs-toho/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/colby.somerville/projects/dibs-toho/node_modules/chromedriver
Output:
Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_mac64.zip
Saving to file: /Users/colby.somerville/projects/dibs-toho/node_modules/chromedriver/npmtmp/78.0.3904.70/chromedriver/chromedriver_mac64.zip
Received 782K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 4704K...
Received 5488K...
Received 6272K...
Received 7056K...
Received 7312K total.
Extracting zip contents
ChromeDriver installation failed Error extracting archive: Error: Target directory is expected to be absolute
```
However, `npm i chromedriver@78.0.1` _does_ work.

Without knowing more about it, I'd guess this commit https://github.com/giggio/node-chromedriver/commit/f331bbe997cd31f7286b0a7b712c27dcace10a42, where it seems `npm_config_tmp` is preferred over `os.tmpdir()`, has messed up the yarn install.

I'm on macos `10.14.6` and yarn `1.17.3`

**Comment by giggio** [comment]
I tested on Windows and it worked. I don't have a Mac easily now.

What is the value of your `npm_config_tmp`? Maybe it is configured incorrectly? Can you try different values?

It makes sense to give priority to `npm_config_tmp`, as it is explicitly set by the user.

**Comment by CSomerville** [comment]
Ah, thanks for the quick response. Turns out we do have a (5 year old) line in our `.npmrc`: `tmp=./npmtmp`. Changing it to an absolute path fixed the chromedriver install, though I'm inclined to just delete the line and see what happens 😄 . I'm still puzzled by the discrepancy between yarn and npm, but I consider my issue resolved and if someone else encounters this I don't believe it to be node-chromedriver issue.
Thanks again!
