### ISSUE TITLE
chromedriver 78.0.1 crash on RHEL 7.7

### ISSUE THREAD

**Issue by taitelman** [giggio/node-chromedriver#240]
just updated my dependencies to chromedriver `78.0.1`
when calling the executable:```/home/myproj/node_modules/chromedriver/bin/chromedriver```
I get

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/myproj/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

```
switched back to `78.0.0` and all is working fine:
```
Starting ChromeDriver 78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}) on port 9515
```

**Comment by giggio** [comment]
I can't repro it, but it must have something to do with f331bbe, so your temp settings might be incorrect. Maybe related to #238? Can you check?

**Comment by taitelman** [comment]
interesing. installing `npm i chromedriver@78.0.1` will work fine .
when running afterwards ```./chromedriver 
Starting ChromeDriver 78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800})```

**Comment by giggio** [comment]
So, the installation works with both `78.0.1` and `78.0.0`? The executable is installed on both cases? It is supposed to be the same binary.

**Comment by giggio** [comment]
Closing as can't repro. If you can find the repro steps, please post them here.
