### ISSUE TITLE
Chromedriver ChromeDriver 79.0.3945.36 missed in the package.json

### ISSUE THREAD

**Issue by YevheniiaMazur** [giggio/node-chromedriver#241]
On 18th of November, 2019 new chrome driver 79.0.3945.36 was released, but currently, it is not available in the time of updating the driver by command 
`npm install chromedriver -CHROMEDRIVER_VERSION=79.0.3945.36`
![errMessage](https://user-images.githubusercontent.com/27342505/70525351-d188ef00-1b4f-11ea-8ac7-f97bc7fa126e.jpg)

Please, add the support of the latest ChromeDriver version

**Comment by giggio** [comment]
The command is incorrect, it should be:

```bash
npm install chromedriver --chromedriver_version=79.0.3945.36
```

But #242 already closed it, I'm publishing it now.
