### ISSUE TITLE
CHROMEDRIVER_VERSION=LATEST downloads an older version

### ISSUE THREAD

**Issue by wvanvugt-speedline** [giggio/node-chromedriver#244]
When I set the chromedriver version to latest, it currently downloads version 78, even though the latest is 79. This means that even with version `79.0.0` of this package, with the LATEST flag set, it will still download version 78. If I remove the flag, it downloads version 79 as expected. I have tried all 3 methods for specifying the version number (.npmrc, environment variable, and install command switch), and all produce this result.

I am guessing this package finds the latest version via https://chromedriver.storage.googleapis.com. In case the behavior of this issue is affected by content at that url changing, I have attached a copy of what I currently see there: [chromedriver.storage.googleapis.txt](https://github.com/giggio/node-chromedriver/files/3951862/chromedriver.storage.googleapis.txt)

**Comment by giggio** [comment]
This is because the latest file has not been updated, and we find the latest from it:
https://chromedriver.storage.googleapis.com/LATEST_RELEASE

I'm not sure how to solve this. Is there another way to find the latest version?

**Comment by giggio** [comment]
More context from https://chromedriver.chromium.org/downloads/version-selection:

> In addition, the version of ChromeDriver for the current stable release of Chrome can be found at https://chromedriver.storage.googleapis.com/LATEST_RELEASE. However, using on this file may be less reliable than methods described above.

I'm not sure where is the issue tracker for Chromedriver itself, but this is clearly a problem on their end.

**Comment by xcao-riffyn** [comment]
I downloaded the latest binary and copy it to node_modules/chromedriver/bin and node_modules/chromedriver/lib/chromedriver/

**Comment by giggio** [comment]
With the latest changes you have an option to specify a major version like `LATEST_80`, or detect Chromedriver's version. Also, the `LATEST` file from Chromedriver points to the correct version.
