### ISSUE TITLE
It won't install on a ARM 32 bit

### ISSUE THREAD

**Issue by ychamare** [giggio/node-chromedriver#245]
root@axcf2152:/opt# npm install chromedriver --chromedriver-force-download

> chromedriver@79.0.0 install /opt/node_modules/chromedriver
> node install.js

Only Linux 64 bits supported.
npm WARN enoent ENOENT: no such file or directory, open '/opt/package.json'
npm WARN opt No description
npm WARN opt No repository field.
npm WARN opt No README data
npm WARN opt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@79.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@79.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/root/.npm/_logs/2019-12-13T10_27_54_024Z-debug.log

I appreciate any guidance

**Comment by giggio** [comment]
ChromeDriver is only compatible with 64 bits on Linux, to understand which of the OS/processor makes the installation fail on your machine, please run the following:

````bash
echo "OS architecture: $(uname -m)"; echo "Processor architecture: $(uname -p)"
````

Arm 32 is also not supported.

**Comment by ychamare** [comment]
Thanks for replying. unfortunately, I am locked to an ARM 32 device, is there any alternatives that you may know ??

**Comment by giggio** [comment]
Not that I'm aware. You might find some answer on Chromedriver's repo.
