### ISSUE TITLE
DETECT_CHROMEDRIVER_VERSION doesn't work on mac

### ISSUE THREAD

**Issue by kellyselden** [giggio/node-chromedriver#247]
I'm trying out the new feature. It works on windows and linux, but fails on mac:

```
ChromeDriver installation failed TypeError: Cannot read property '1' of null
    at /Users/travis/build/CrowdStrike/faltest/node_modules/chromedriver/install.js:59:75
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

https://travis-ci.org/CrowdStrike/faltest/jobs/642838144#L204
https://github.com/CrowdStrike/faltest/pull/237

**Comment by giggio** [comment]
I don't have a Mac around right now. I see you are using Yarn 1. I just tested on Windows with Yarn 2 and it worked. Can you try to debug to help understand the problem?

**Comment by giggio** [comment]
I just tried Yarn 2 on Windows using Node 8, and it does not work. The regex works, though. Yarn 1 on Linux also does not work. Can you try to upgrade Node? Node 8 is no longer supported.

**Comment by kellyselden** [comment]
I could, but this library and it's consumers still support node 8. Eventually I will drop it, but not yet.

**Comment by jonathansamines** [comment]
@giggio I could reproduce this even with Node 12 while using MacOS. Please take a look at #248.

**Comment by ksathyanm** [comment]
@kellyselden @giggio @jonathansamines Shouldn't this be fixed in https://github.com/testimio/chrome-version itself?

**Comment by giggio** [comment]
Yes, this should be fixed on https://github.com/testimio/chrome-version.

@benjamingr I remember you mentioned that you were involved in this project, are you able to verify this bug?

**Comment by benjamingr** [comment]
We were able to verify the bug - the `\n` was just not important the way we used chrome-version internally.

CC @eladrkatz who actually did the work 😅

**Comment by giggio** [comment]
@kellyselden I just published 79.0.3 with the fix from testimio/chrome-version. Would you please test it so we can verify?

**Comment by kellyselden** [comment]
You removed node 8 support, so I guess I'll be locked on 79.0.2 for a while and won't be able to use this feature :(

**Comment by giggio** [comment]
I just removed Node.js 8 from the build, but the build was passing.
The build was passing on Node.js 8 until recently: https://dev.azure.com/giggio/node-chromedriver/_build/results?buildId=278&view=results
I'm assuming this code also works on 8. Let me know if it does not.

**Comment by kellyselden** [comment]
Looks like everything is now happy https://github.com/CrowdStrike/faltest/pull/237. Thank you everyone for helping!
