### ISSUE TITLE
Chromedriver version 80.0.1 doesn't work with latest google chrome version

### ISSUE THREAD

**Issue by marcdomain** [giggio/node-chromedriver#253]
Please how do I find permanent fix to chromedriver version incompatibility with the google-chrome version on system?
The challenge of having to always update chromedriver version is not scalable.

**Comment by giggio** [comment]
You can detect Chrome version. Would that work?

https://github.com/giggio/node-chromedriver/blob/master/README.md#detect-chromedriver-version

**Comment by marcdomain** [comment]
Thanks @giggio for the response.
I used chromedriver version 77 in package.json, so I got the`exports.version = '77.0.3865.40'`. By adding the `detect_chromedriver_version=true` to my `.npmrc` I expected it to ignore the version 77 and install the corresponding version to my chrome (version 80).
However, it fails. It still picks the installed version 77.

**Comment by giggio** [comment]
Even when you reinstall? Can you post the logs?
