### ISSUE TITLE
extract-zip has a dependency to mkdir@0.5.2, that has a dependency to minimist@0.0.8 which has a security issue

### ISSUE THREAD

**Issue by andreasmarkussen** [giggio/node-chromedriver#254]
Chromedriver depends on extract-zip@1.6.7, which has a security problem.

Extract-zip has a dependency on mkdir@0.5.2, that has a dependency on minimist@0.0.8 which has a security issue

The problem is not easy to fix since extract-zip is not maintained. 

The fix should be that someone should take over extract-zip and ensure that it is up to date. 

Does anyone have suggestions to how to cope with a situation like this?

**Comment by dmarczydlo** [comment]
From security reason are you planning to update `minimist` dependencies?

**Comment by andrewiggins** [comment]
extract-zip has been updated: maxogden/extract-zip#88

**Comment by giggio** [comment]
I just updated and released a fix.
