### ISSUE TITLE
Timed out issue with webdriverio V6

### ISSUE THREAD

**Issue by guptapranay** [giggio/node-chromedriver#259]
With wdio V6, chrome driver generating [WARNING] & [SEVERE] category logs with message:
```
[1586080644.335][WARNING]: Timed out connecting to Chrome, retrying...                                                                
[1586080648.445][WARNING]: Timed out connecting to Chrome, retrying...                                                                
[1586080654.989][SEVERE]: Timed out receiving message from renderer: 0.100         
```                                
Issue is not producible, if I use `selenium-standalone` as a service.

**Comment by giggio** [comment]
Is the Chromedriver binary where it is suposed to be?

**Comment by guptapranay** [comment]
It's been installed with npm i. I guess yes.

I was reading few articles earlier, where it was mentioned , this is the issue specific to latest version of chromedriver and chrome browser version of 80. Degrading the version works. Here is the mention of that:

https://stackoverflow.com/questions/60114639/timed-out-receiving-message-from-renderer-0-100-log-messages-using-chromedriver

**Comment by giggio** [comment]
If this is the case, this is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
