### ISSUE TITLE
Version 81 failing to install; complains about already existing directory

### ISSUE THREAD

**Issue by HairMachine** [giggio/node-chromedriver#264]
Installing older versions of chromedriver (80 and below) seem to work absolutely fine.

However when I try to npm install version 81, I get the following error:

ChromeDriver installation failed Error: Error extracting archive: Error: EEXIST: file already exists, mkdir '/tmp/81.0.4044.69/chromedriver'
    at extractDownload (/path/to/repo/node_modules/chromedriver/install.js:282:11)

This happens even when I manually delete the directory it's complaining about. It happens regardless of whether I install locally in a project or globally. The only thing I'm doing is "npm install chromedriver" with 81.0.0 set in the package.json. Other methods of install do the same thing (version-latest etc.).

I'm on Ubuntu 18.04 (64 bit). Node version 10.10.0. Any ideas?

**Comment by giggio** [comment]
Hi, can you try versions `80.0.0`, `80.0.1`, and `80.0.2`? They all had small differences, maybe we can pinpoint the problem.

**Comment by HairMachine** [comment]
Hi! I can confirm that the same thing seems to happen with 80.0.2, but 80.0.1 and 80.0.0 both seem to work fine.

**Comment by HairMachine** [comment]
Update: I fiddled around in my package-lock.json, setting older version for extract-zip and managed to get it working (following this: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions).

I must say I don't know for sure, thanks to the mysteries of npm (my package-lock.json completely changed and now has no reference to either chromedriver or the extract-zip library...) but I guess I don't mind too much!

**Comment by giggio** [comment]
Are you on Node 10 or above? 80.0.2 and above are incompatible.

**Comment by HairMachine** [comment]
Yes, I believe so. node -v output:

v10.10.0

**Comment by giggio** [comment]
That is not expected. This is a `file already exists` error, so maybe there is an option to override the file? I'll check.

**Comment by giggio** [comment]
Ok, overwrite is on by default, and the file is written with enough permissions to let you edit it. Maybe you've run it as root, and now you can't access it? Can you check?

Source:
https://github.com/maxogden/extract-zip#options

**Comment by HairMachine** [comment]
Doesn't seem to be anything related to file permissions that's obvious. I can pretty easily replicate it from scratch by removing the folder it's complaining about completely, then just running npm install -g chromedriver; no sudo. It creates this directory structure:

- tmp
- - 81.0.4044.69
- - - chromedriver
- - - - chromedriver_linux64.zip

When it tries to unzip chromedriver_linux64.zip, that error appears.

Owner of the folder and everything within is my standard non-sudo user, permissions are 664.

**Comment by giggio** [comment]
If the file exists, it should try to use the same file, not overwrite it.
This is what I get on Ubuntu 19.10, with Node 13.13.0 and npm 6.14.4:

````
❯ npm i

> chromedriver@81.0.0 install /home/giggio/p/rabiscos/tc/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/tmp/81.0.4044.69/chromedriver/chromedriver'.
Copying to target path /home/giggio/p/rabiscos/tc/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /home/giggio/p/rabiscos/tc/node_modules/chromedriver/lib/chromedriver/chromedriver
npm WARN tc@1.0.0 No description
npm WARN tc@1.0.0 No repository field.

added 72 packages from 98 contributors and audited 100 packages in 1.323s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
````

I can't repro it. Can you try to debug it?

**Comment by arickGrootveld** [comment]
I'm having this same issue, not sure what progress has been made on this since the last update, but I can share more information if it helps

**Comment by HairMachine** [comment]
OK, I've figured out the problem, you can see a reference to it here: https://github.com/nodejs/node/issues/24698

It seems that there were some bugs in node 10 that meant the "recursive" option of fs.mkdir is broken in some versions despite existing (the idea there is it's not supposed to throw this error if that flag is set, but it does).

Solution is basically to update node - I don't know exactly when it was added properly but there's some suggestion it was 10.12, then some others say it's broken again in 10.15. Maybe it's just best to support only node 11+!

Long story short is the solution is to upgrade node.

**Comment by giggio** [comment]
Ok. Were you able to use a 10.x that works?
We test it on 10.x, the latest, in build time. It seems to be working with the latest 10.

**Comment by HairMachine** [comment]
Sorry, I just upgraded to 12 so I'm not sure! I think there is definitely some set of 10.x versions that work, but more than that I have no idea.

**Comment by giggio** [comment]
@HairMachine ok, so your scenario is fixed, we could close the issue, then.

@arickGrootveld can you share your setup? Are you also on Node 10? Do you get the same error?

**Comment by HairMachine** [comment]
Yeah happy to close it. Thanks!
