### ISSUE TITLE
if download and install chromedriver through circleci throw an error

### ISSUE THREAD

**Issue by wovalles** [giggio/node-chromedriver#270]
I was using this repo for a long time but recently(yesterday) when I try to install the chromedriver through CircleCI throw the next error: 

![Screen Shot 2020-05-21 at 10 15 19 AM](https://user-images.githubusercontent.com/43178445/82574746-8d196a80-9b55-11ea-8199-997e36ff0d4a.png)

Details of the env:
 - CircleCI
 - Ubuntu 16.04

Note: I was using the same way.

**Comment by giggio** [comment]
This looks like a duplicate of #264. 

See this comment, it might help you:
https://github.com/giggio/node-chromedriver/issues/264#issuecomment-617645185

Also, read the other comments, they might help you.

**Comment by wovalles** [comment]
Thanks for taking the time the answer it, I'll do it
