### ISSUE TITLE
Chromedriver 83 fails with node 8 version

### ISSUE THREAD

**Issue by woothu** [giggio/node-chromedriver#273]
CI result with node 10/12 tests - passing :
https://github.com/coreui/coreui-free-vue-admin-template/actions/runs/125715253

CI result with node 8/10/12 tests - failed:
https://github.com/coreui/coreui-free-vue-admin-template/actions/runs/125714074

**Comment by giggio** [comment]
Yes, it is not supported. See the readme for supported versions.
