### ISSUE TITLE
Can't install in mac book pro m1

### ISSUE THREAD

**Issue by lifubang** [giggio/node-chromedriver#289]
When installing node-chromedriver in mac book pro m1, I got this error message:
```
Only Mac 64 bits supported.
```

I add a console log msg, and find that the value of `process.arc` is `arm64`.

Do we have the plan to fix this problem? Thanks.

**Comment by lifubang** [comment]
Oh, maybe not relate to mac m1, but relate to the node version v15.2.1
When I use node 13.0.1, it can be installed successful.

**Comment by giggio** [comment]
This is the latest release: https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.20/
It shows:

* chromedriver_linux64.zip
* chromedriver_mac64.zip
* chromedriver_win32.zip

I'm not sure mac64 works with ARM, have you tested it?

**Comment by lifubang** [comment]
Sorry, I can't visit any google websites because of the firewall's rule.

**Comment by giggio** [comment]
@lifubang Ok, can you try and download from a mirror and verify if it works?

**Comment by lifubang** [comment]
> I'm not sure mac64 works with ARM, have you tested it?

I have tested it, it works very well.
![image](https://user-images.githubusercontent.com/783424/100111152-c3d79100-2ea8-11eb-876c-ab30fbc4bc5f.png)
