### ISSUE TITLE
chromedriver_cdnurl doesn't use noproxy npm setting

### ISSUE THREAD

**Issue by ArjenKorevaar** [giggio/node-chromedriver#293]
At our company, we use a proxy server to download packages from nmpjs.org.

Certain files however, are blocked by the proxy server, so for that reason we need to host chromedriver internally and use chromedriver_cdnurl to download chromedriver during install from our intranet webserver.

The install.js of chromedriver uses the proxy, even though the chromedriver_cdnurl matches the noproxy setting. This results in a proxy server error page being downloaded as chromedriver_win32.zip which subsequently fails to unzip.

The solution would be to check the noproxy setting and only use the proxy settings if the chromedriver_cdnurl does not match the noproxy pattern.

**Comment by giggio** [comment]
@ArjenKorevaar I believe this was already satisfied by PR #291. Would you please verify?

**Comment by ArjenKorevaar** [comment]
Hi @giggio, thanks for your reply. I hadn't seen #291 yet, but if I understand correctly, #291 uses the proxy-from-env package to determine if, and if so what, proxy url is to be used based on environment variables. I will need to test if this also works with the NPM noproxy setting, as we work with project-specific .npmrc files. I'll look into this monday and let you know.

**Comment by ArjenKorevaar** [comment]
Hi @giggio #291 does indeed seem to solve this issue! I have closed the PR.
