### ISSUE TITLE
When trying to install chrome from another directory it fails

### ISSUE THREAD

**Issue by gemelgb** [giggio/node-chromedriver#295]
**Error message:**

ChromeDriver installation failed Error: Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.

**Callstack:**

ChromeDriver installation failed Error: Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.
    at safeCheck (C:\Users\AppData\Roaming\npm\node_modules\wdio\node_modules\del\index.js:37:9)
    at mapper (C:\Users\AppData\Roaming\npm\node_modules\wdio\node_modules\del\index.js:73:4)
    at C:\Users\AppData\Roaming\npm\node_modules\wdio\node_modules\p-map\index.js:57:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Analysis:**
The problem comes from one of your dependencies and how you call it. The del package.
```
Package: https://www.npmjs.com/package/del
File: Index.js ln 107-110

if (!force) {
	safeCheck(file, cwd);
}
```
This is a default check and the only way around it is to set the force option to true. Currently in your install.js:
```
async function copyIntoPlace(originPath, targetPath) {
  await del(targetPath);
....
}
```
can we add the option force or set it default to true? This way will be possible  call chromedriver install.js through any other directory.

Thank you.

**Comment by giggio** [comment]
Why do you want to call install.js from other directory? The purpose of this package is to install Chromedriver in the node_modules directory and make it available to be run with the app.

**Comment by gemelgb** [comment]
Hi,

Chromedriver is a dependency on a tool that is installed globally, in that case this error appears. It doesnt make sense to ask my users to go to the globally install repository path and ask them to install chromedriver... Dont see why allowing this can be a problem...or?

Thank you.

**Comment by giggio** [comment]
It could be a problem if the destination could vary. But I checked the structure of the code, the location is always a known location. I'll do an update and release it.
