### ISSUE TITLE
Getting error : "A device attached to the system is not functioning. (0x1F)"

### ISSUE THREAD

**Issue by RitikPandey1** [giggio/node-chromedriver#296]
I'm using chrome driver with selenium and getting these errors 

![err](https://user-images.githubusercontent.com/57366926/103514940-afb58500-4e93-11eb-8898-02f4482e3f47.PNG)

These error messages mess my test logs ,how can I remove them from console?

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
