### ISSUE TITLE
Chromedriver 88.0.4324.96 import error

### ISSUE THREAD

**Issue by kmiasko** [giggio/node-chromedriver#302]
After upgrading chromedriver to version 88.0.4324.96 i've error running my tests

```
[test:execute] > protractor ./protractor.conf.js
[test:execute]
[test:execute] [07:03:20] I/launcher - Running 1 instances of WebDriver
[test:execute] [07:03:20] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:55923/devtools/browser/43110cb6-7b46-46d5-9650-0185aea38e3b
[test:execute] [07:03:22] E/launcher - Error: C:\tests\node_modules\@nodelib\fs.scandir\src\adapters\fs.spec.ts:1
[test:execute] import * as assert from 'assert';
[test:execute] ^^^^^^
[test:execute]
[test:execute] SyntaxError: Cannot use import statement outside a module
[test:execute]     at Module._compile (internal/modules/cjs/loader.js:892:18)
[test:execute]     at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[test:execute]     at Object.require.extensions.<computed> [as .ts] (C:\tests\node_modules\ts-node\src\index.ts:851:44)
[test:execute]     at Module.load (internal/modules/cjs/loader.js:812:32)
[test:execute]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[test:execute]     at Module.require (internal/modules/cjs/loader.js:849:19)
[test:execute]     at require (internal/modules/cjs/helpers.js:74:18)
[test:execute]     at C:\tests\node_modules\jasmine\lib\jasmine.js:89:5
[test:execute]     at Array.forEach (<anonymous>)
[test:execute]     at Jasmine.loadSpecs (C:\tests\node_modules\jasmine\lib\jasmine.js:88:18)
```

```
C:\tests [staging ≡ +0 ~2 -0 !]> node --version
v12.13.0
```

**Comment by giggio** [comment]
Looking at your call stack, it doesn't look like an error in Chromedriver, there isn't anything from it there. Does it work if you rollback to the previous version?

**Comment by kmiasko** [comment]
@giggio Yeah, it works ok, when i revert install. I can see that installing new chromedriver (last one was 86 in my repo) updates some dependencies in package-lock.json and error is somewhere in the dependencies tree (looks like del -> globby -> fast-glob -> @nodelib)

[package-lock.json.txt](https://github.com/giggio/node-chromedriver/files/5875615/package-lock.json.txt)

**Comment by giggio** [comment]
Looking at the graph here: https://npm.anvaka.com/#/view/2d/chromedriver
I can see it is:
Chromedriver -> del -> globby -> fast-glob -> @nodelib/fs.walk -> @nodelib/fs.scandir

I did update `del` about 1.5 months ago: https://github.com/giggio/node-chromedriver/commit/9cd029d6b1426c118dcc01c8abdd6d02b36af55e
This was release `87.0.3`. Can you verify if the previous version (.2) works?

I guess you can update only one of the deps by installing a newer version of it. Have you tried it? Maybe updating Jasmine or `@nodelib/fs.scandir` directly?
