### ISSUE TITLE
Detecting the Edge Version for download. 

### ISSUE THREAD

**Issue by harishraok** [giggio/node-chromedriver#307]
Hello,

The msedgedriver does not download the latest version of msedge driver. I have edge version at 89.0.774.63 but during install it always seems to download 87.0.664.66. How do I set it to download the version that's been installed on the machine?

I have also tried installing using npm install msedgedriver --edgechromiumdriver_version=LATEST. I am getting error
C:\Work\AWeb>npm install msedgedriver --edgechromiumdriver_version=LATEST

> msedgedriver@87.0.13 install C:\Work\AdvantageWeb\node_modules\msedgedriver
> node install.js

 :\Users\harish\AppData\Local\Temp\��8 9 . 0 . 7 7 4 . 6 3
 \msedgedriver is not writable: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\harish\\AppData\\Local\\Temp\\��8\x009\x00.\x000\x00.\x007\x007\x004\x00.\x006\x003\x00\r\x00\n\x00\\msedgedriver'
 :\Users\harish\AppData\Local\Temp\��8 9 . 0 . 7 7 4 . 6 3
 \msedgedriver is not writable: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\harish\\AppData\\Local\\Temp\\��8\x009\x00.\x000\x00.\x007\x007\x004\x00.\x006\x003\x00\r\x00\n\x00\\msedgedriver'
 tmp\��8 9 . 0 . 7 7 4 . 6 3
 \msedgedriver is not writable: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\tmp\\��8\x009\x00.\x000\x00.\x007\x007\x004\x00.\x006\x003\x00\r\x00\n\x00\\msedgedriver'
 :\Work\AdvantageWeb\node_modules\msedgedriver\tmp\��8 9 . 0 . 7 7 4 . 6 3
 \msedgedriver is not writable: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Work\\AdvantageWeb\\node_modules\\msedgedriver\\tmp\\��8\x009\x00.\x000\x00.\x007\x007\x004\x00.\x006\x003\x00\r\x00\n' +
 ...
Can not find a writable tmp directory, please report issue on https://github.com/uex-io/node-msedgedriver/issues/ with as much information as possible.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msedgedriver@87.0.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msedgedriver@87.0.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Looks like there is an issue with the code.

Thanks and Regards,
Harish Rao

**Comment by giggio** [comment]
This not the repo for msedgedriver.

**Comment by harishraok** [comment]
Hello Giggio,
The msedgedriver is forked from chromedriver and the git-hub links to chromedriver and it shows that you are the author. https://github.com/uex-io/node-msedgedriver

I dont see a way to raise issue on it. 

Can you please take a look into it?

Thanks and Regards,
Harish Rao

**Comment by giggio** [comment]
@harishraok I'm not the maintainer, and it seems that the owner of that repo has disabled issues. I can't fix it.
Maybe try opening a Pull request to get @uex-io attention.
