### ISSUE TITLE
Bug: Certificate errors when trying to Install this project's NPM package 

### ISSUE THREAD

**Issue by pr3tori4n** [giggio/node-chromedriver#309]
As the summary, mentions, I'm trying to install this dependency and I'm getting a certificate error.

`yarn global add chromedriver`
`yarn global v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.com/chromedriver: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "C:<pathto>\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.`

As a temporary workaround, I was able to get the install to work by disabling strict-ssl. But that's not something I'm ok with keeping disabled long term.

I am behind a corporate proxy, but I have my certifications [properly configured](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file).

This is the only dependency in my project that has this issue.

**Comment by giggio** [comment]
I can't repro it.
Instalation happens from Npm's website. I don't manage that.
I seriously doubt this is an issue with this project. If there is a problem it could be with Npm itself, not with this package.
I suggest you try:
* Updating your Yarn
* Running it from outside the company network

Let me know how it goes. In any case, I need repro steps.

Also, I have never tested this project as a global tool and the behavior is undefined and not supported.
