### ISSUE TITLE
Installation still fails on Macbook M1

### ISSUE THREAD

**Issue by vivshaw** [giggio/node-chromedriver#316]
Hello, we're having the same issue as #304 despite being on an M1 compatible version of `chromedriver`.

Chromedriver version: `90.0.1`

Error message: 

```
error /Users/petermurphy/codingHome/mercury/hannahexperimentwithm1nix/mercury-web/node_modules/chromedriver: Command failed.                                                                             
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/petermurphy/codingHome/mercury/hannahexperimentwithm1nix/mercury-web/node_modules/chromedriver
Output:
Only Mac 64 bits supported.
```

`uname -m`: `arm64`

`process.arch` in Node: `arm64`

Please let me know if there's any additional info I can provide that'd be helpful, or any workarounds I should attempt.

**Comment by giggio** [comment]
Hi @vivshaw, I don't have an M1 Mac to verify the issue. Would you please try to debug `install.js`? If `process.arch` is `arm64` it should work, I can't see what else could be going on.

**Comment by martinpuertas** [comment]
@vivshaw did you get to make it work?

**Comment by thenishchalraj** [comment]
I don't think so @martinpuertas. Did you find some solution? I ran into this issue right now, and followed the thread ending here. Still the progress for M1 is slow, I'ld say.

**Comment by martinpuertas** [comment]
sorry for late reply, but we saw that the 'validatePlatform' function in 'install.js' is not looking for the right chromedriver for M1, which is stored as '{chromedriverVersion}/chromedriver_mac64_m1.zip' so I downloaded and installed it manually.
besides, I had some errors starting webdriver-manager with chromedriver in 90.0.1 and found that with the chromedriver version "^91.0.1" these errors are gone
