### ISSUE TITLE
npm install fails @2.15.1 with "Invalid protocol"

### ISSUE THREAD

**Issue by danieloltmanns** [giggio/node-chromedriver#32]
On upgrade from 2.15.0 to 2.15.1, I'll get this error

    $ npm install
    -
    > chromedriver@2.15.1 install C:\cygwin64\home\path\to\node_modules\chromedriver
    > node install.js

    Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_win32.zip
    Saving to C:\cygwin64\tmp\chromedriver\chromedriver_win32.zip
    Receiving...
    Error with http request: Error: Invalid protocol: my.proxy:
    ChromeDriver installation failed undefined

**Comment by alexdavid** [comment]
Hi, could you post the string you have set in your `HTTP_PROXY` env variable?

**Comment by giggio** [comment]
Also probably related to #30 and #31.

**Comment by alexdavid** [comment]
@danieloltmanns any update on this? Are you still running into the same issue?

**Comment by rahuljawale** [comment]
Getting similar issue . I tried installing request module but that did not help too.

```
Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip
Saving to /var/folders/mw/v3n8q5350j7bxkddcjbfr2b80000gn/T/chromedriver/chromedriver_mac32.zip
Receiving...
Error with http request: Error: connect ENETUNREACH
ChromeDriver installation failed undefined
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/scratch/.npm-packages/bin/npm" "install" "chromedriver"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.15.1 install: `node install.js`
npm ERR! Exit status 1
```

I can provide more details.

**Comment by giggio** [comment]
Version 2.15.2 has been published. Please verify if it solves the problem.

**Comment by rahuljawale** [comment]
Yup! It works now. No more LIFECYCLE issue. Thanks. :+1:

**Comment by giggio** [comment]
Ok, I will close the issue. @danieloltmanns If you still find the problem let us know.
