### ISSUE TITLE
chromedriver for chrome 92

### ISSUE THREAD

**Issue by ilhan007** [giggio/node-chromedriver#321]
There is new stable version of Chrome - 92, do you have plans to provide a chromedriver for it?

**Comment by giggio** [comment]
I'm waiting for it to become stable. See https://chromedriver.chromium.org/

**Comment by ilhan007** [comment]
Ok, thanks.

**Comment by ilhan007** [comment]
Hi @giggio last thing, do you have any idea when it is going to become "stable"?

**Comment by giggio** [comment]
No idea, and it seems they are lagging behind. I just published it.
