### ISSUE TITLE
[Issue] Socket Hang Up

### ISSUE THREAD

**Issue by JandenMa** [giggio/node-chromedriver#324]
Hey sorry, not sure if this issue is related to `nightwatch` or `chromedriver`, but I met it yesterday. 
When I run the e2e test by `nightwatch` in the CircleCI docker, it throws `socket hang up` issue, see the pic below:
![image](https://user-images.githubusercontent.com/27947587/130556362-fbddf8d4-5a2f-4342-8bb9-851ef4aeb38a.png)

Does anyone have some suggestions or ideas? thx in advance!

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
