### ISSUE TITLE
Read error is throws if there is a directory in the zip file

### ISSUE THREAD

**Issue by ReneZumtobel** [giggio/node-chromedriver#325]
We use this package to download chromedriver from our custom repository and had a folder inside of the zip file. This leads to the following error:
`Error: EISDIR: illegal operation on a directory, read Emitted 'error' event on ReadStream`

It seems that the reason for this is that the copyIntoPlace function does not check if the file that it wants to copy is a directory and if so handles it accordingly. So the problem is in the promise of `install.js(Line 308 - 313)`

**Comment by giggio** [comment]
This repo will only extract a zip file that is in the format published by the Chromedriver team. It will not support custom zip formats, so, if you have a folder inside the zip and that is not what is in the default zip from the Chromedriver team, you need to adapt your custom .zip file to be compatible.

**Comment by ReneZumtobel** [comment]
True, but while the official one does not, the one that is provided from electron does.

**Comment by giggio** [comment]
The Electron team publishes a custom Chromedriver binary?

**Comment by ReneZumtobel** [comment]
They have a list of release chromedriver zips that people can use. I tried to use the following https://github.com/electron/electron/releases/tag/v13.2.2

This is what we have on our own custom repo. We rename the zips to match the names downloaded by the package. But those zips have folders in them, that is why the option to copy folders would be appreciated.

Because then we would not have to deal with the hassle to delete and rezip the folder all the time. I can implement the changes and submit a PR if that is fine.

**Comment by giggio** [comment]
Ok, I just downloaded this file from the Electron release, and while it does have folders, the chromedriver binary is not in one. `chromedriver.exe`, which is the file being looked for, is at the zip root.
The other files and directories inside the zip were ignored and the file was copied as expected.
Are you sure you're not changing the zip structure?

**Comment by giggio** [comment]
Ok, I got what the error is, it is not that there are directories in the zip, is that we can't handle a zip with several files and directories. This should be a simple fix.

**Comment by giggio** [comment]
Fixed and published to Npm as 92.0.2.

**Comment by ReneZumtobel** [comment]
Thank you very much.
