### ISSUE TITLE
Cannot update chromedriver: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by nmattia** [giggio/node-chromedriver#357]
I'm on chromedriver `97.0.0`, but running `npm update chromedriver` fails with the following:

```
npm ERR! TypeError: Cannot read properties of null (reading 'toString')
npm ERR!     at isEmulatedRosettaEnvironment (/Users/nicolas/proj/node_modules/chromedriver/install.js:359:14)
npm ERR!     at getMacOsRealArch (/Users/nicolas/proj/node_modules/chromedriver/install.js:343:35)
npm ERR!     at validatePlatform (/Users/nicolas/proj/node_modules/chromedriver/install.js:89:25)
npm ERR!     at Object.<anonymous> (/Users/nicolas/proj/node_modules/chromedriver/install.js:34:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1103:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47
```

I'm on macOS Monterey 12.3 (Intel), node `v16.14.0`, npm `8.3.1`

**Comment by giggio** [comment]
This is line 359:

https://github.com/giggio/node-chromedriver/blob/e8b610d985377cd7154f6cce254671824986f6b2/install.js#L358-L359

This is running `sysctl -in sysctl.proc_translated`, can you try running this command in the terminal and posting here what happens?
I don't have a Mac to try it.

**Comment by nmattia** [comment]
Here's what I get:

```
$ sysctl -in sysctl.proc_translated
$ echo $?
0
$ sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'
$ echo $?
1
```

which seems to be [expected](https://stackoverflow.com/questions/65346260/get-real-architecture-of-m1-mac-regardless-of-rosetta). I'm guessing the correct way to go about this is to first check that the return code is `0`; I'll give this a try now.

**Comment by nmattia** [comment]
I've added a fix in https://github.com/giggio/node-chromedriver/pull/358 though I haven't tested it on M1 macs
