### ISSUE TITLE
Issues with chromedriver 1.0.3

### ISSUE THREAD

**Issue by dnoliver** [giggio/node-chromedriver#369]
Hi, 

I started running into issues with my Selenium tests after an upgrade of chrome 
Looks like it is a known issue in Selenium and in Chromium

https://github.com/SeleniumHQ/selenium/issues/10799
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121

This comment reports that bumping version to 1.0.4 solved it https://github.com/SeleniumHQ/selenium/issues/10799#issuecomment-1170666166

I guess node-chromedriver would need to provide a v1.0.4 to address it

**Comment by giggio** [comment]
Chromedriver 104 is still in beta, this library only releases stable versions. You can still use the version parameter to install a different version, or wait for 104 to come out of beta.
See:
https://github.com/giggio/node-chromedriver#versioning
