### ISSUE TITLE
Chromedriver.exe is missing from node_modules\chromedriver

### ISSUE THREAD

**Issue by ericoliveros** [giggio/node-chromedriver#373]
Hi,

I am having issue on running my cucumberjs test because Chromedriver.exe is missing from generated chromedriver folder under node_modules.
I am using Windows 10 and chromedriver 103.0.0

![image](https://user-images.githubusercontent.com/15687310/179456566-293532a2-fcaf-4fa1-b8a3-18543816ecf2.png)

Hope you can help me with this. Thanks

**Comment by giggio** [comment]
When you install this package with `npm install chromedriver` it will be installed in `node_modules/chromedriver/lib/chromedriver/chromedriver.exe`. If it is not there, please send the logs for `npm install chromedriver`.

**Comment by ericoliveros** [comment]
Hi @giggio,

It seems like it is a network issue. Some security is blocking the chromedriver.exe to be installed. So I will just close this  issue. Thanks
