### ISSUE TITLE
No chromedriver 105

### ISSUE THREAD

**Issue by yogeshgadge** [giggio/node-chromedriver#378]
Chrome version 105 is out there and so it the chromedriver version (https://chromedriver.storage.googleapis.com/index.html?path=105.0.5195.52/) but I can't seem to get that. 

Is 104 version of this package supposed to provide 105 version of chrome version ?

**Comment by yogeshgadge** [comment]
Saw 2 PRs which should get me going when merged

**Comment by giggio** [comment]
Published now.
