### ISSUE TITLE
No such object: chromedriver/106.0.5249.61/chromedriver_mac64_m1.zip

### ISSUE THREAD

**Issue by jennylia** [giggio/node-chromedriver#387]
THe file name    const fileName = `chromedriver_${platform}.zip`;
determined this variable name chromedriver_mac64_m1
and you can see it's not here:
https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.61/

Can we make this more robust please

**Comment by jennylia** [comment]
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/jenny.lian/workspace/web-ux/e2e-tests-v2/node_modules/chromedriver
Output:
Your Chrome version is 106.0.5249.61
Finding Chromedriver version.
Chromedriver version is 106.0.5249.61.
Compatible ChromeDriver version is 106.0.5249.61
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
Saving to file: /var/folders/lj/2v1tkxv16qd532dy67wlx_zr0000gq/T/106.0.5249.61/chromedriver/chromedriver_mac64_m1.zip
Error status code: 404
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/106.0.5249.61/chromedriver_mac64_m1.zip</Details></Error>
ChromeDriver installation failed Error: Error with http(s) request: Error: Request failed with status code 404
    at requestBinary (/Users/jenny.lian/workspace/web-ux/e2e-tests-v2/node_modules/chromedriver/install.js:274:11)

**Comment by giggio** [comment]
Yes, this was fixed in #386. If it is not the case please comment with repro steps __with the latest version__.
