### ISSUE TITLE
ChromeDriver 107 release

### ISSUE THREAD

**Issue by imann24** [giggio/node-chromedriver#388]
Hi, may I inquire when the project is releasing a version that supports ChromeDriver 107?

**Comment by giggio** [comment]
When it becomes stable. It is currently in beta.

**Comment by imann24** [comment]
Thanks very much!

**Comment by prust** [comment]
@giggio @imann24: FYI, Chrome 107 [was released](https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_25.html) to the stable channel today.

**Comment by giggio** [comment]
Resolved by #389.
