### ISSUE TITLE
npm install throws error: npm ERR! Failed at the chromedriver@2.20.0 install script 'node install.js'.

### ISSUE THREAD

**Issue by lipikakumar** [giggio/node-chromedriver#39]
terminal displays the following:

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
|
> chromedriver@2.20.0 install chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.20/chromedriver_mac32.zip
Saving to /var/folders/qv/mqkpjkqj5wj6ypy0h05vm1kczfky_t/T/chromedriver/chromedriver_mac32.zip

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "chromedriver"
npm ERR! node v0.10.40
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.20.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chromedriver@2.20.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

**Comment by giggio** [comment]
You are having a `ECONNRESET` error, this is a network error, not a chromedriver error.
