### ISSUE TITLE
107.0.2: Node 12 install fails: fs.rmSync is not a function

### ISSUE THREAD

**Issue by gschueler** [giggio/node-chromedriver#391]
It seems 107.0.2 broke node 12 in our environment:

```
ChromeDriver installation failed TypeError: fs.rmSync is not a function
    at copyIntoPlace (/app/node_modules/chromedriver/install.js:312:6)
    at install (/app/node_modules/chromedriver/install.js:73:11)
```

using 107.0.1 works ok

**Comment by giggio** [comment]
This project only supports Node.js versions that are also supported. Version 12 is no longer supported since April 2022.

**Comment by mviger** [comment]
Should engines in the package.json be updated then?

Currently it is
```
"engines": {
    "node": ">=10"
 }
```

**Comment by giggio** [comment]
Yes. I'll open an issue.
