### ISSUE TITLE
Fix engines in package.json

### ISSUE THREAD

**Issue by giggio** [giggio/node-chromedriver#393]
It should show only supported Node.js versions.
Is there a way to do this automatically? For example, a "supported" flag or something?

**Comment by sforsberg** [comment]
@giggio Are you referring to the `engines` package field: https://github.com/giggio/node-chromedriver/blob/main/package.json#L43-L45 ? 

Somewhat related to this, the latest version of this package cannot install on node v12 (potentially node v10 as well). 

When trying to install latest using node `v12.22.1`, we are seeing the following error:

```
...
> chromedriver@107.0.2 install /Users/sforsberg/dev/mfe/product-search-mfe/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/zw/3tl53yxn0wdggf051z8h7t8h0000gq/T/107.0.5304.62/chromedriver/chromedriver'.
ChromeDriver installation failed TypeError: fs.rmSync is not a function
    at copyIntoPlace (/Users/sforsberg/dev/mfe/product-search-mfe/node_modules/chromedriver/install.js:312:6)
    at install (/Users/sforsberg/dev/mfe/product-search-mfe/node_modules/chromedriver/install.js:73:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    ...
``` 

I am going to try rolling back to a previous version for now.

**Comment by adtakle** [comment]
@sforsberg I was seeing the same issue with node `v16.14.2`. I created a separate issue for this: #395
