### ISSUE TITLE
npm ERR! ChromeDriver installation failed TypeError: fs.rmSync is not a function

### ISSUE THREAD

**Issue by OdedBaruch** [giggio/node-chromedriver#394]
npm ERR! Failed at the chromedriver@107.0.2 install script,
Would you please help, till version 107.0.1 - everything was fine, I guess that because fs.rmsync considered relatively new function instead of fs.unlinkSync?
the past 4 days we went back to using 107.0.1 , so we can't get latest changes incase you'll have them.

**Comment by mviger** [comment]
It looks like the recommendation is to upgrade your version of Node.js to at least version 14.  This was previously addressed in #391

**Comment by OdedBaruch** [comment]
Thanks, I missed that one... I figured
