### ISSUE TITLE
Upgrade to v108

### ISSUE THREAD

**Issue by fifle** [giggio/node-chromedriver#401]
New Chrome browser stable version (Version 108.0.5359.71, released on 29.11.2022) has been automatically rolled out for browser users, so there's a version mismatch for those who run the npm package that contains v107 now. Also, ChromeDriver version has been [updated 2 days ago.](https://chromedriver.storage.googleapis.com/108.0.5359.71/notes.txt). 

@giggio Please upgrade the package to v108 ASAP :)

**Comment by giggio** [comment]
Published now, commit b2924ef75712ef9b923d3ae61b52ae8b33704878.
