### ISSUE TITLE
latest chromedriver 109.0.0 is not compatible with latest macOS chrome 109.0.5414.87

### ISSUE THREAD

**Issue by satabdisikdar** [giggio/node-chromedriver#403]
Description:
Latest chromedriver 109 is compatible with latest ubuntu chrome, but not working with latest macOS chrome. 
It throws below error:
```
VError: a BeforeAll hook errored, process exiting: cucumber.conf.js:19: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 107"
```

This is a bug! Kindly look into it on priority!

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
