### ISSUE TITLE
update for chrome 110

### ISSUE THREAD

**Issue by kabaneridev** [giggio/node-chromedriver#408]
@giggio The stable version of ChromeDriver [110.0.5481.77](https://chromedriver.storage.googleapis.com/index.html?path=110.0.5481.77/) was updated today along with the Chrome version. https://chromedriver.chromium.org/
<img width="726" alt="Screenshot 2023-02-08 at 12 16 19" src="https://user-images.githubusercontent.com/48051231/217515019-01e4fd7b-a90f-412f-9236-337a4c7f5eb4.png">

Could you please provide an update?

**Comment by giggio** [comment]
Updated on e1e01c6.
