### ISSUE TITLE
Chromedriver download url changing for versions 115+

### ISSUE THREAD

**Issue by benm071** [giggio/node-chromedriver#416]
Chrome has changed their download site/formats as of 115 to something like

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.13/win32/chromedriver-win32.zip

Therefore, the built in googleapis site no longer works, and it's not seemingly possible to use the environment variables to create a compatible URL.  The closest we can come is to define, for example:

CHROMEDRIVER_CDNURL=https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.13

and

CHROMEDRIVER_VERSION=win32

however the target filename on the Chrome CDN has now been changed to 
chromedriver-win32.zip rather than the 
chromeidriver_win32.zip built into node-chromedriver. (Note the change from _ to -)
I don't think this can be overcome without a node-chromedriver code change

A patch needs to be released for node-chromedriver that either can build the proper CDN URL for chromedrivers after 114 or allow a configurable target CDN filename to be overridden using an environment variable so we can hack together the proper download.

See https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE

**Comment by giggio** [comment]
Thanks for the heads up, @benm071! I have posted a question there to clear some points. After those are answered and can move forward and change the install script to work with 115+ versions, which are not out yet (and are planned only to mid-July).

**Comment by giggio** [comment]
@benm071 I changed the code to work with both versions up to 114 (using the current and now being phased out urls) and the new ones that start with 115. You can already try it by specifying the version, there are several ways to do it. It was published as `114.0.2`.
