### ISSUE TITLE
Make dlBaseUrl configurable, same as cdnUrl

### ISSUE THREAD

**Issue by austlane** [giggio/node-chromedriver#417]
In the `downloadFile` function. Please allow for `dlBaseUrl` to be overridden (npm config, env variable, npmrc, etc).
This was available via the `chromedriver_cndurl` config for versions before 114, but was lost with the transition to the new download method.

This config is extremely useful for air-gapped environments with local mirrors.

**Comment by giggio** [comment]
Yes, I'll do that. I released this earlier so everyone could try it as it is. 
As the new Chrome version is not out yet I believe we have some time to work on it.

**Comment by giggio** [comment]
@austlane I have introduced another configuration that will allow for the binaries url to be set. I'll just wait for the gh actions to work and I'll release it.
