### ISSUE TITLE
v114 doesn't honor CHROMEDRIVER_CDNURL env var

### ISSUE THREAD

**Issue by kumarrishav** [giggio/node-chromedriver#418]
As a workaround, I had to downgrade to v113

**Comment by nikdoof** [comment]
Looks like its now changed to `chromedriver_legacy_cdnurl`, but the documentation hasn't been updated.

Change went in in https://github.com/giggio/node-chromedriver/commit/61189b24992ed1627dd3601be2d545db20ec4175

**Comment by giggio** [comment]
@kumarrishav you can go back to `114.0.1`.
@nikdoof good catch I'll update the docs.
