### ISSUE TITLE
Only Mac 64 bits supported.

### ISSUE THREAD

**Issue by wjyzhixing** [giggio/node-chromedriver#425]
Only Mac 64 bits supported.
how to resolve this problem?
<img width="726" alt="image" src="https://github.com/giggio/node-chromedriver/assets/36620969/4c30ff97-f305-4d24-bfe8-78c222bd77f1">

**Comment by giggio** [comment]
ChromeDriver is only compatible with 64 bits on Mac.

You can see the latest binaries on their site, notice only 64 bits is available: https://googlechromelabs.github.io/chrome-for-testing/
