### ISSUE TITLE
How can I stop the driver from blocking my scripts?

### ISSUE THREAD

**Issue by anasouardini** [giggio/node-chromedriver#430]
I'm using the Chromedriver with selenium, and whenever there is an "error", the driver blocks my script injection using selenium and hangs my app.

I don't think that the driver should concern itself with this level of details, especially since it's not a GUI or TUI app, it's hard to debug using CLI, I don't even get the line of the supposed error.

This makes my debugging take 3x the time required.

I wonder if there is an option to stop this... feature??

I've tried to use the ESlint library but I'm new to it, I need to learn lots of quirks to be able to intercept the error before the driver catches it and blocks my app.

Thanks.

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).

**Comment by anasouardini** [comment]
I just want to post issue link here just in case someone is trying to the do the same.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=4561

It hasn't been processed yet at the time of posting this.
