### ISSUE TITLE
chromedriver 119 loads a blank browser

### ISSUE THREAD

**Issue by arthurATgrowers** [giggio/node-chromedriver#437]

**Comment by arthurATgrowers** [comment]
![image](https://github.com/giggio/node-chromedriver/assets/149695208/b52af9c8-c336-4f8d-8d72-21a32f57d118)

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
