### ISSUE TITLE
npm i - > Only Mac 64 bits supported.

### ISSUE THREAD

**Issue by Romick2005** [giggio/node-chromedriver#438]
I am on Apple Mac mini M1 machine with arm64 so why it is not working for me?

```
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Only Mac 64 bits supported.
npm verb exit 1
npm verb unfinished npm timer reify 1700121505404
npm verb unfinished npm timer reify:build 1700121542431
npm verb unfinished npm timer build 1700121542432
npm verb unfinished npm timer build:deps 1700121542432
npm verb unfinished npm timer build:run:install 1700121542442
npm verb unfinished npm timer build:run:install:node_modules/chromedriver 1700121542442
npm verb code 1
```

**Comment by giggio** [comment]
Can you try to get the values from these functions?
https://github.com/giggio/node-chromedriver/blob/de961e34e023afcf4fa5c0faeeec69aaa6c3c815/install.js#L417
https://github.com/giggio/node-chromedriver/blob/de961e34e023afcf4fa5c0faeeec69aaa6c3c815/install.js#L431

You can see it is executing `uname` and `sysctl`. Also check Node's `process.arch`.

**Comment by Romick2005** [comment]
Sorry for this. This error was reported after installing [eventemitter3](https://github.com/primus/eventemitter3) and there were no direct dependency on chromedriver, but only this error were thrown:
```
user@Mac-mini eventemitter3 % npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/user/repo/eventemitter3/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Only Mac 64 bits supported.

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-11-16T20_31_52_243Z-debug-0.log
```
After more precise look I find out that it has dependency on old [sauce-test](https://github.com/ForbesLindesay-Unmaintained/sauce-test) that is actually dependent on [chromedriver@2.26.1](https://github.com/ForbesLindesay-Unmaintained/sauce-test/blob/7c671b3321dc63aefc00c1c8d49e943ead2e7f5e/package.json#L10C5-L10C31) that is why it was failing.
So I I [forked sauce-test](https://github.com/Romick2005/sauce-test) module and updated [chromedriver](    "chromedriver": "^119.0.1",) to the latest and now I able to install eventemitter3 and do benchmark compare.
Thank for such a great module, that latest version is compatible and works even with that oldest code!
Great job!
