### ISSUE TITLE
Wrong URL being used to download older Chrome versions

### ISSUE THREAD

**Issue by jstavanja-veza** [giggio/node-chromedriver#445]
Some containers have the Chrome driver version necessity for version: 

> npm install chromedriver --no-save --detect_chromedriver_version
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Your Chrome version is 120.0.6099.71
npm ERR! Finding Chromedriver version.
npm ERR! Chromedriver version is 120.0.6099.109.
npm ERR! Compatible ChromeDriver version is 120.0.6099.109
npm ERR! Saving to file: /tmp/120.0.6099.109/chromedriver/chromedriver-linux64.zip
npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
npm ERR! Downloading from file:  https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip

Since the new URL is hardcoded in your latest commits, the pulling of the driver is being done from the wrong URL.

Chrome for testing actually uses a function to determine which URL should be used. Perhaps you want to adopt a similar strategy for this module as well: https://github.com/GoogleChromeLabs/chrome-for-testing/commit/dd90f461197402d01208a690b58f8a7776db6e7c

**Comment by Rinzwind** [comment]
We’ve had the error as well:

```
$ CHROMEDRIVER_VERSION=120.0.6099.109 npm install chromedriver
[…]
npm ERR! Downloading from file:  https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/mac-x64/chromedriver-mac-x64.zip
npm ERR! Error status code: 404
```

As a workaround, we set `CHROMEDRIVER_CDNBINARIESURL` as follows:

```
$ CHROMEDRIVER_VERSION=120.0.6099.109 CHROMEDRIVER_CDNBINARIESURL=https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing npm install chromedriver

added 35 packages in 1s
```

**Comment by giggio** [comment]
Maybe in the last 7 hours the Chromedriver team fixed it. It seems to be working. Could you please test? I did not change anything.

**Comment by Rinzwind** [comment]
The URL mentioned in the error message I gave works again:
https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/mac-x64/chromedriver-mac-x64.zip

So the workaround can be dropped:

```
$ rm -r "$TMPDIR/120.0.6099.109"; CHROMEDRIVER_VERSION=120.0.6099.109 npm install chromedriver

added 35 packages in 2s
```

**Comment by giggio** [comment]
Ok, I'm closing the issue, if you find it is broken again let me know and I'll reopen it.
