### ISSUE TITLE
wrong chromedriver version when imported from node_modules/chromedriver

### ISSUE THREAD

**Issue by metaver5o** [giggio/node-chromedriver#446]
https://github.com/giggio/node-chromedriver/blob/6d7c2f1c3c28146fed153facbe2dd2d7d9319d88/lib/chromedriver.js#L18

npm ERR!     data: "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/LATEST_RELEASE_121.0.6167</Details></Error>"

**Comment by giggio** [comment]
@metaver5o What is the error, exactly? I need repro steps.
