### ISSUE TITLE
Is there an issue with CDN?

### ISSUE THREAD

**Issue by peter-dough** [giggio/node-chromedriver#451]
Just a few hours ago, I started receiving this error when installing chromedriver via npm.

**Steps to Reproduce**:
npm install chromedriver@120.0.1

**Sample Error**:
```
09:02:18  npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
09:02:18  npm ERR! Downloading from file:  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip
09:02:18  npm ERR! Error status code: 500
```

**Comment by scscoville** [comment]
Same issue

**Comment by mhelgerson** [comment]
Getting the same issues, completely blocking builds now :(

**Comment by peter-dough** [comment]
Came across [this](https://github.com/giggio/node-chromedriver?tab=readme-ov-file#for-versions--115-1) in the readme. I suppose this applies to >120.0.0 now? Going to try and set `CHROMEDRIVER_CDNBINARIESURL=https://storage.googleapis.com/chrome-for-testing-public` to see if it makes a difference.

**Comment by scscoville** [comment]
@peter-dough 
Adding this portion to .npmrc worked for me:
`CHROMEDRIVER_CDNBINARIESURL=https://storage.googleapis.com/chrome-for-testing-public`

**Comment by giggio** [comment]
Hey everyone, this is fixed after `121.0.1`. The chrome team changed the binary url. See #448.

**Comment by peter-dough** [comment]
@giggio I believe the issue is with downloading an older version of chromedriver. Switching to a new driver doesn't resolve the original issue reported is more of a workaround...

**Comment by giggio** [comment]
@peter-dough yes, the older versions won't work anymore, as the Chromedriver team changed the urls.
I just published a new version which will use their endpoints to determine the download url, so this should not happen in the future, but we can't fix the older versions.

**Comment by yazicii** [comment]
hii @giggio I am at the latest version of the library 122.0.3 however I still got the same problem. 

```
Error: Failed downloading chromedriver v122.0.6261.94: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.94/mac-arm64/chromedriver-mac-arm64.zip, retrying ...
``` 

the url is trying to go to the edgedl and the server returns 404. I tried to change the urls with .npmrc but it did not work.

**Comment by giggio** [comment]
@yazicii I just tried on Ubuntu and couldn't repro. The old URL (edgedl...) is not in the install.js file anymore, so I can't think of how it is still trying it.
Also, version `122.0.3` is tied to Chromedriver version `122.0.6261.69`, not version `122.0.6261.94`.
Can you send me repro steps?
