### ISSUE TITLE
 Failed at the chromedriver@2.21.2 install script 'node install.js'.

### ISSUE THREAD

**Issue by BrotherPeng** [giggio/node-chromedriver#46]
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> chromedriver@2.21.2 install D:\Workspaces\VueProjects\testvue1\node_modules\chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
Saving to C:\Users\liyun\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed undefined
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.14332
npm ERR! argv "D:\\Dev\\nodejs\\node.exe" "D:\\Dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "chromedriver@2.21.2"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Workspaces\VueProjects\testvue1\npm-debug.log

**Comment by Razzeee** [comment]
Same here running windows 7. Might work with windows 10, as I use that at home and could install fine yesterday.

**Comment by asktalk** [comment]
the same error on window10

**Comment by alexlukelevy** [comment]
Save here on Win 7. Only seems to happen on `npm install` of my package.json. Works fine when individually installed `npm install chromedriver`.

**Comment by tb01923** [comment]
an issue for me - Ubuntu.

```
> chromedriver@2.21.2 install /home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
ChromeDriver installation failed undefined
npm verb lifecycle chromedriver@2.21.2~install: unsafe-perm in lifecycle true
npm verb lifecycle chromedriver@2.21.2~install: PATH: /home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/bin/node-gyp-bin:/home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver/node_modules/.bin:/home/tbrown/Documents/projects/NodeGoat/node_modules/.bin:/home/tbrown/.nvm/v6.2.2/bin:/home/tbrown/.nvm/v6.2.2/bin:/u01/app/oracle/product/11.2.0/xe/bin:/home/tbrown/.rvm/gems/ruby-2.2.1/bin:/home/tbrown/.rvm/gems/ruby-2.2.1@global/bin:/home/tbrown/.rvm/rubies/ruby-2.2.1/bin:/usr/bin/mh:/home/tbrown/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/share/scala/bin:/home/tbrown/.rvm/bin:/home/tbrown/.rvm/bin
npm verb lifecycle chromedriver@2.21.2~install: CWD: /home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver
npm info lifecycle chromedriver@2.21.2~install: Failed to exec install script
npm verb unlock done using /home/tbrown/.npm/_locks/staging-e3298a83de80104c.lock for /home/tbrown/Documents/projects/NodeGoat/node_modules/.staging
npm WARN optional Skipping failed optional dependency /forever/forever-monitor/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /grunt-nodemon/nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm verb stack Error: chromedriver@2.21.2 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid chromedriver@2.21.2
npm verb cwd /home/tbrown/Documents/projects/NodeGoat
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/home/tbrown/.nvm/v6.2.2/bin/node" "/home/tbrown/.nvm/v6.2.2/bin/npm" "install" "-verbose"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tbrown/Documents/projects/NodeGoat/npm-debug.log
```

Glad to provide more details...

**Comment by HashemQolami** [comment]
Fixed the same issue on Ubuntu by https://github.com/vuejs/vue-router/issues/261#issuecomment-218618180

**Comment by binarymist** [comment]
Did the suggested fix work @tb01923 ?

**Comment by giggio** [comment]
I can't repro it. Can anyone that is having the problem debug it?

**Comment by fuchao2012** [comment]
mac os same question

node version 5.7.0

**Comment by giggio** [comment]
Just tried it on Windows 10, it is working fine. We need repro steps, everyone. It helps no one to just say "me too". Send repro steps so we can try to fix it.
<img width="588" alt="npmi" src="https://cloud.githubusercontent.com/assets/334958/17427016/c5335548-5ab3-11e6-80f1-3aed8a863325.PNG">

**Comment by peter-mouland** [comment]
this version works fine for me

**Comment by giggio** [comment]
@peter-mouland Yes, that is being fixed. They pulled the 32 bit version from the repo. We will be updating it today. The update is already in the `master` branch.

**Comment by giggio** [comment]
As I am not getting repro steps for this issue, I am closing it. Anyone who finds repro steps please post them so we can look into it.

**Comment by FrankStraif** [comment]
I had the same issue, and for me it was a "behind proxy" issue.
The install.js file is using a proxy from npms 'proxy' setting. Adding "proxy=http://...." to my .npmrc solved the issue for me.
I found it by checking what was the content of the downloaded zip file: it wan an html error page and not the zip. A very common error if you do not check the http result of a http-get call.

**Comment by fnlctrl** [comment]
@FrankStraif Thank you so much! Disabling proxy(and a `npm cache clear`) solved the problem.

**Comment by guwenbin1991** [comment]
@FrankStraif  
### I have set the proxy configuration through npm config
```
npm config set proxy and https-proxy
```
but it doesn't work, I'm working behind the proxy server because of the network limit
***so does it work for you when add the proxy server:port through npm config set***
***or it need to add .npmrc file***

**Comment by deschant** [comment]
I am having the same issue on a debian 8 server. 

> chromedriver@2.33.2 install /root/digitix/node_modules/chromedriver
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/digitix/node_modules/chromedriver/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/opt/nodeJs/bin/node" "/opt/nodeJs/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.33.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.33.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/digitix/npm-debug.log

**Comment by philling** [comment]
Have a try: npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
