### ISSUE TITLE
Regression: CHROMEDRIVER_FILEPATH doesn't work

### ISSUE THREAD

**Issue by jan-molak** [giggio/node-chromedriver#462]
Hey @giggio

It looks like v122.0.0 introduced a regression (also present in v123) similar to #424, where specifying `CHROMEDRIVER_FILEPATH` breaks the installation process.

I believe the culprit is the `return` statement on line `66`:

https://github.com/giggio/node-chromedriver/blob/85cd3fa15eb3cbd6f29bcad89576b99d04cdd78e/install.js#L61-L79

This return statement prevents the script from proceeding to line `75` and copying the existing user-specified binary to `chromedriver/lib/chromedriver`:
https://github.com/giggio/node-chromedriver/blob/85cd3fa15eb3cbd6f29bcad89576b99d04cdd78e/install.js#L75-L77

Since the binary is never copied to the correct destination, calling `require('chromedriver').path` returns a path that points to a non-existent location, which then confuses automation frameworks:

https://github.com/giggio/node-chromedriver/blob/85cd3fa15eb3cbd6f29bcad89576b99d04cdd78e/lib/chromedriver.js#L48-L52

I believe that to solve this, the install script should copy the user-specified binary to the expected location.

**Comment by giggio** [comment]
Yes, this is most likely a bug. It came from the refactoring I did earlier. I see you submitted a PR, I'll take a look into it.

**Comment by giggio** [comment]
I just fixed it and will release momentarily. If the fix does not work for you, please let me know.

**Comment by jan-molak** [comment]
Thanks @giggio, I'll try it in a moment :+1:

**Comment by jan-molak** [comment]
Looking good, thanks for the quick fix, @giggio!
