### ISSUE TITLE
chromedriver ^124 can not be found

### ISSUE THREAD

**Issue by SuZhou-Joe** [giggio/node-chromedriver#467]
![image](https://github.com/giggio/node-chromedriver/assets/13493605/e136d075-b706-43dc-943a-587ca5d90808)
Chrome released v124 while chromedriver is still at 123.0.4. A `npm publish` is needed.

**Comment by DougHigashi** [comment]
I'm still getting this error
![image](https://github.com/giggio/node-chromedriver/assets/55817197/07d6f56e-1dac-484c-9c6b-318b0e45614d)

**Comment by AMoo-Miki** [comment]
I was under the impression that merged version bumps were auto-published. The publish job has been skipped for a bunch of versions now.

**Comment by SMillerDev** [comment]
Yeah, it appears (https://www.npmjs.com/package/chromedriver?activeTab=versions) that this version never made it to NPM

**Comment by giggio** [comment]
Closed on 1f78491
