### ISSUE TITLE
Axios error while installing chromedriver@123.0.0 with node v18.18.2

### ISSUE THREAD

**Issue by biswajitsundara** [giggio/node-chromedriver#471]
**Steps to Reproduce**

- The node version is 18.18.2
- Execute command npm i chromedriver@123.0.0

**Actual Result**

- The installation fails
- ChromeDriver installation failed AxiosError: Request failed with status code 404

**Expected Result**

- It should install the chromedriver package & shouldn't throw any error

**Debugging**
* The problem was not with the previous version 122 and started only after 123
* On reviewing the logs looks like its not finding the resource at the end point
http://chromedriver.storage.googleapis.com/chrome-for-testing/123.0.6312.58.json and the GET call is failing
<img width="851" alt="image" src="https://github.com/giggio/node-chromedriver/assets/49075041/f34c3f41-e7c8-43b4-b623-de7e3f7b3c02">

**Comment by giggio** [comment]
Can you try with newer versions?
Can you post logs?

**Comment by biswajitsundara** [comment]
Hi @giggio 
Thanks for your response. The latest version works fine
`npm i chromedriver@latest`
Closing the issue.
