### ISSUE TITLE
Can't start new session, unable to receive message from renderer

### ISSUE THREAD

**Issue by YOO629** [giggio/node-chromedriver#493]
Hi, first off thanks for the package and maintaining it. We've been using this in conjunction with Nightwatch and I'm passing in the downloaded chromedriver path via require('chromedriver').path to Nightwatch to tell it where the chromedriver is. I'm not really sure where to start troubleshooting this as I've made sure the chromedriver package is up to date and the java version we're using is compatible (openjdk 11). What could possibly be causing these issues? They seemed to just appear about 2 days ago

Ubuntu 18.04
Node: 16.13.1
chromedriver@latest
google-chrome-stable@128.x

This seems like some sort of compatibility issue but I can't seem to figure out exactly what is incompatible.

Starting ChromeDriver 128.0.6613.84 (606aa55c7d687518d34b55accc5a71ea0bd28727-refs/branch-heads/6613@{#1335}) on port 34236
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 34236.
[1724437489.096][SEVERE]: Unable to receive message from renderer
18:24:49.110 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=128.0.6613.84)
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'ip-redacted', ip: 'redacted', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1103-aws', java.version: '11.0.19'
Driver info: driver.version: unknown

Thanks,
Joe

**Comment by giggio** [comment]
@YOO629 You are seeing the chromedriver's log, so this this is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://code.google.com/p/chromedriver/issues/).
