### ISSUE TITLE
Updating to the latest version of chromedriver

### ISSUE THREAD

**Issue by tflint-rethink** [giggio/node-chromedriver#51]
This has not been updated to use the latest version of chromedriver, 2.22.

This version is suppose to fix issues with timeouts and hangs, a major issue for us.

I would like to have this npm package update for accessing this version.

**Comment by Dzenly** [comment]
+1. I am also waiting for fixes with weird hangings.

**Comment by giggio** [comment]
Released last Sunday. See #49.
