### ISSUE TITLE
use of npm strict-ssl configuration

### ISSUE THREAD

**Issue by sfbwalder** [giggio/node-chromedriver#54]
The download of the chrome driver always uses rejectUnauthorized = true when the protocol is https.  We need the ability to set it to false.  Having it set to npm's strict-ssl setting is sufficient for our need.  This can work by adding this line shown below in ```getRequestOptions()```:

``` JS
function getRequestOptions(proxyUrl) {
  ...
  //set https setting to match npm's setting
  options.rejectUnauthorized = !!process.env.npm_config_strict_ssl
  ...
  return options
}
```
We may be able to provide a PR soon.

**Comment by giggio** [comment]
Closed on #55
