### ISSUE TITLE
npm install failing on mac

### ISSUE THREAD

**Issue by kunwardeep** [giggio/node-chromedriver#61]
This looks more like a broken build than anything else. How.. i am not sure (we need a new release tag?). When i download the code and compile it goes and downloads chromedriver_mac64. But when i use npm install chromedriver . It fails because it is trying to download chromedriver_mac_32 which does not exist

`sudo npm install --force
Password:
npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json jobseeker-jobapply@1.0.31 No license field.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
-
> chromedriver@2.23.0 install /Users/kbedi/code/jobseeker-jobapply/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.23/chromedriver_mac32.zip
Saving to /Users/kbedi/code/jobseeker-jobapply/node_modules/chromedriver/chromedriver/chromedriver_mac32.zip
Receiving...
ChromeDriver installation failed undefined
chromedriver@2.23.0 node_modules/chromedriver
├── kew@0.5.0
├── adm-zip@0.4.7
├── rimraf@2.5.4 (glob@7.0.5)
└── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.3, semver@4.3.6, nopt@3.0.6, osenv@0.1.3, config-chain@1.1.10)`

The package.json says `"name": "chromedriver",
  "version": "2.23.0",
  "keywords": [
    "chromedriver",
    "selenium"
  ],`

But the install.js has the logic `if (platform === 'linux') {
  if (process.arch === 'x64') {
    platform += '64'
  } else {
    platform += '32'
  }
} else if (platform === 'darwin') {
  platform = 'mac32'
} else if (platform !== 'win32') {
  console.log('Unexpected platform or architecture:', process.platform, process.arch)
  process.exit(1)
}
`

**Comment by giggio** [comment]
Already fixed on #57. Will publish in a moment.

**Comment by giggio** [comment]
Working version published to NPM as version `2.23.1`
