### ISSUE TITLE
Install failed on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by lndj** [giggio/node-chromedriver#62]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.23.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.23.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
[npm-debug.txt](https://github.com/giggio/node-chromedriver/files/440792/npm-debug.txt)

**Comment by giggio** [comment]
@lndj we need more info. We need repro steps. Please check the other issues and see if you can find more info, some people had problems with proxy settings. I'll close the issue until we have the repro steps.
