### ISSUE TITLE
mac 10.11.6 installed fail

### ISSUE THREAD

**Issue by hainuo** [giggio/node-chromedriver#63]
[npm-debug.log.txt](https://github.com/giggio/node-chromedriver/files/463137/npm-debug.log.txt)

i got error using `npm install chromedriver --chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver`.
i don't know  how to dealwith it.

**Comment by giggio** [comment]
@hainuo we need more info. We need repro steps. Please check the other issues and see if you can find more info, some people had problems with proxy settings. I'll close the issue until we have the repro steps.
