### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by asktalk** [giggio/node-chromedriver#67]
**error  and log:**

Downloading http://npm.taobao.org/mirrors/chromedriver/2.24/chromedriver_win32.zip
Saving to C:\Users\asktalk\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed undefined
npm info lifecycle chromedriver@2.24.1~install: Failed to exec install script
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\2.enviroment_domain\\2.nodejs.env\\node.exe" "D:\\2.enviroment_domain\\2.nodejs.env\\node_modules\\npm\\bin\\npm-cli.js" "install" "chromedriver" "--chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

**Comment by meintjesbekker** [comment]
I experience the same problem with the latest version of npm and node. Please see the included npm-debug.txt (log at the end as well):

E:\Temp>npm install chromedriver --chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> chromedriver@2.24.1 install E:\Temp\node_modules\chromedriver
> node install.js

Downloading http://npm.taobao.org/mirrors/chromedriver/2.24/chromedriver_win32.zip
Saving to C:\Users\MBekker1\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed undefined
npm WARN enoent ENOENT: no such file or directory, open 'E:\Temp\package.json'
npm WARN Temp No description
npm WARN Temp No repository field.
npm WARN Temp No README data
npm WARN Temp No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "chromedriver" "--chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Temp\npm-debug.log

Log file:
[npm-debug.txt](https://github.com/giggio/node-chromedriver/files/523833/npm-debug.txt)

**Comment by giggio** [comment]
There is an error on the server. I inspected the error and here it is:

````
"Error with http request: { server: 'nginx/1.4.6 (Ubuntu)',\n  date: 'Sat, 29 Oct 2016 19:25:49 GMT',\n  'content-type': 'text/html; charset=utf-8',\n  'content-length': '173',\n  connection: 'close',\n  vary: 'Accept-Encoding',\n  location: 'http://cdn.npm.taobao.org/dist/chromedriver/2.25/chromedriver_win32.zip',\n  'x-response-time': '4',\n  'strict-transport-security': 'max-age=15768000' }"
````

I will update the package to show the error starting now, probably version 2.25.1.

**Comment by atif089** [comment]
@giggio Dumb question but, why does it work for Mac but not for Windows?

**Comment by liuweifeng** [comment]
@giggio , 
```
ChromeDriver installation failed Error with http request: { server: 'nginx/1.4.6 (Ubuntu)',
  date: 'Wed, 08 Feb 2017 10:57:09 GMT',
  'content-type': 'text/html; charset=utf-8',
  'content-length': '177',
  connection: 'close',
  vary: 'Accept-Encoding',
  location: 'http://cdn.npm.taobao.org/dist/chromedriver/2.27/chromedriver_linux64.zip',
  'x-response-time': '3',
  'strict-transport-security': 'max-age=15768000' }
```

it's not a server error, but a `302` location redirect, from `http://npm.taobao.org/mirrors/chromedriver/2.27/chromedriver_linux64.zip` to `http://cdn.npm.taobao.org/dist/chromedriver/2.27/chromedriver_linux64.zip`.

In our code https://github.com/giggio/node-chromedriver/blob/master/install.js#L221 ,  non 200 state codes are considered to be wrong.

**Comment by giggio** [comment]
Yes, this is the expected behavior, as it works with the Google server.
