### ISSUE TITLE
Fallback on another proxy setting?

### ISSUE THREAD

**Issue by Kikketer** [giggio/node-chromedriver#71]
In an enterprise setting we are behind a proxy, but are using an internal NPM gateway/repo.  So we don't set our proxy settings for things when we do `npm install`, and it's actually preferred that way since there are internal dependencies we are using.

Your library is using the proxy setting from the npm config (good work) but now it seems we need to be able to proxy ONLY the `http.get` and nothing else.

Would it be possible to update to have it check two different npm config settings?  Or some other way we can designate a proxy setting when you do an `http.get`?

**Comment by giggio** [comment]
I think we only do http and https get. We don't post or put. What do you propose?

**Comment by Kikketer** [comment]
Yeah the GET is fine, and good work checking the proxy settings (we found many libraries don't do that).  But of course times change and now we don't want to set proxy settings for everything except the `http.get()`... sigh

So could you add something simple like `npmsettings['http-proxy'] || npmsettings['html-get-proxy']` ?

I'm not sure if there's a known pattern or setting that other projects use to set proxies that don't use the standard `proxy` attribute in the npm settings.  I can set my npm settings to have something like `npm config set html-get-proxy <myproxyurl>`

We can make up anything if you want, just not sure if there's a known way today that we could copy.

**Comment by Kikketer** [comment]
Maybe even an environment variable?  Something that I can use to override on the fly

**Comment by giggio** [comment]
We will only need to http get when installing. What you could do is set the proxy environment variable when you are installing, and then unset it later.
I don't think this is in scope for what this package is doing. It seems a specific problem that may be solved working the app code.
