### ISSUE TITLE
Use https by default

### ISSUE THREAD

**Issue by giggio** [giggio/node-chromedriver#77]

**Comment by teddmason** [comment]
Hi, this change has broken our usage of the npm module.  When installing we are getting an error and it can't download the chromedriver. We think that it is due to our server using a proxy and setting the url to https is causing an issue.

```
Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
ChromeDriver installation failed Error with http request: { server: 'squid/3.5.12',
  'mime-version': '1.0',
  date: 'Wed, 07 Dec 2016 11:20:12 GMT',
  'content-type': 'text/html;charset=utf-8',
  'content-length': '3604',
  'x-squid-error': 'ERR_UNSUP_REQ 0',
  vary: 'Accept-Language',
  'content-language': 'en',
  'x-cache': 'MISS from ip-',
  'x-cache-lookup': 'NONE from ip-',
  via: '1.1 ip-(squid/3.5.12)',
  connection: 'close' }
```

**Comment by giggio** [comment]
@teddmason Try forcing the url:

````bash
npm i chromedriver --chromedriver_cdnurl=https://chromedriver.storage.googleapis.com
````

If it works, then you are sure that you have an infrastructure problem. See https://github.com/giggio/node-chromedriver#custom-binaries-url as a way to working around it using other options beyond the `chromedriver_cdnurl` argument.
Also, why would a proxy block https? Tha is weird.
This has been a security update requested by users.

**Comment by davidblackburn** [comment]
@giggio 
Looking at the install.js this references 'proxy' on line 62 -
    _return requestBinary(getRequestOptions(conf.get('proxy')), downloadedFile)_
This in turn is only pulling in _process.env.HTTP_PROXY_ from npmconf
https://github.com/npm/npmconf/blob/master/config-defs.js#L192
I think this should be updated to https-proxy, which will check for all variables. Otherwise as @teddmason error shows you get a http --> https invalid request from the proxy

**Comment by giggio** [comment]
@davidblackburn Yes, it makes sense we use `https-proxy`. But that will use the https proxy even for http requests, and that might break other people. I will see if I can find a way to integrate both.

**Comment by giggio** [comment]
Will follow up the proxy problem on #78.
