### ISSUE TITLE
Issue when running acceptance tests via npm run

### ISSUE THREAD

**Issue by nemanja-tosic** [giggio/node-chromedriver#82]
Hello,

I have a setup with cucumber.js where i run acceptance tests on selenium via node, on a Windows machine. I have noticed an issue when running the mentioned tests via `npm run acceptance-test`. Mainly, npm run adds the node_modules/.bin folder to the beginning of the PATH, and that folder contains a file called chromedriver, whereas the module adds the binaries to the end of the PATH, so they aren't really used as the .bin folder takes precedence. That being said i'm not sure why as selenium-webdriver asks for chromedriver.exe.

What i did to make it work with `npm run acceptance-test` is basically change this:

`process.env.PATH += path.delimiter + path.join(__dirname, 'chromedriver');`

to this:

`process.env.PATH = path.join(__dirname, 'chromedriver') + path.delimiter + process.env.PATH;`

in lib/chromedriver.js, that is i placed the chromedriver folder to the beginning of the path.

Package versions:

* chromedriver - 2.26.1
* selenium-webdriver - 2.53.3
* selenium-server - 2.53.1

Thanks,
Nemanja

**Comment by giggio** [comment]
We can't change what `npm run` does.
What I suggest you try is add the code to export the variable to the script itself in package.json.
Also, the `chromedriver` script on `.bin` should just execute this module anyways, which will then run the chromedriver.
Also, you can change the path to chromedriver on selenium. Search for the browser options.

**Comment by nemanja-tosic** [comment]
I wasn't suggesting you change what npm does, i was suggesting that you add the binaries to the beginning of the path instead of the end.

**Comment by giggio** [comment]
This could cause problems. We would be breaking everyone who relies on this behavior. If you need that, before you call `start` or start selenium you could update the `path` environment variable yourself, using the `path` exported by the module.

**Comment by nemanja-tosic** [comment]
I managed to get it working for myself, i just wanted to contribute to make it work out of the box, that is by just doing `require('chromedriver');`

For posterity i'm going to write out what i found to be the issue. To reiterate I am on Windos. Selenium by default looks for "chromedriver", npm adds the .bin folder to the path which contains chromedriver and chromedriver.cmd binaries, but the one that actually gets executed is chromedriver - the sh script - which won't really work on Windows. If you delete the chromedriver script everything works fine. That being said, specifying the chromedriver binary path works, so no action is really needed, as you've said.

Sorry to bug you so much BTW, thank you for your replies!
