### ISSUE TITLE
Does not download a different version if run on a different operating system

### ISSUE THREAD

**Issue by fc** [giggio/node-chromedriver#84]
In my case I setup a Linux Vagrant instance that syncs with my local directory on macOS.  It doesn't re-download the chromedriver at all or check if the operating system has changed since the last install.

If you run test-driver.sh it will output something like this:
```
$ ./test-driver.sh
/vagrant_data/example/node_modules/chromedriver/lib/chromedriver/chromedriver: 1: /vagrant_data/example/node_modules/chromedriver/lib/chromedriver/chromedriver: �����/vagrant_data/example/node_modules/chromedriver/lib/chromedriver/chromedriver��!H__PAGEZERO�__TEXT��
```

At the very least, it would be nice to have some kind of sanity check when this happens.  Or, better, perhaps it could download and load the appropriate version depending on what OS it is running on.

Thoughts?

**Comment by giggio** [comment]
The installer will check for `process.platform`, directly from the Node.js core library. If you run `npm install` on the Mac, it will install Mac binaries. You have to run it on a Linux shell.
There is no way the installer can detect you are installing on a Mac, but later running on Linux.
Does that help?
