### ISSUE TITLE
"Path must be a string" error if there's no tmp dir in env

### ISSUE THREAD

**Issue by cheeaun** [giggio/node-chromedriver#86]
Regarding the latest change here: https://github.com/giggio/node-chromedriver/commit/494e7231f69cd9276357676a8302cd0c400ef447#diff-f16acefe4b6553580c43edab685f50f3R87

In my case `process.env.TMPDIR || process.env.npm_config_tmp` returns an `undefined` value which causes a `Path must be a string` error when the value is passed into `path.join` method here: https://github.com/giggio/node-chromedriver/blob/494e7231f69cd9276357676a8302cd0c400ef447/install.js#L93

I can open a PR but not sure what's a good "fallback" value, probably `process.env.TMPDIR || process.env.npm_config_tmp || ''`?

**Comment by giggio** [comment]
Fixed and published now as `2.27.2`.
