### ISSUE TITLE
Chromedriver not finding Chrome binary on a BitBucket Pipelines

### ISSUE THREAD

**Issue by juanbernabo** [giggio/node-chromedriver#87]
Great Gigiio!!!, nice to find you here..

Had a problem and don't know how to solve it. Need to install Chrome on the docker image or chromedriver downloads it?

Thanks in advance!

> elos-app@0.0.1 accept /opt/atlassian/pipelines/agent/build/ClientApp
> node node_modules/chimp/bin/chimp
Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu
[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-59-generic x86_64)]
  message: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-59-generic x86_64)',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-59-generic x86_64)' } }
Error: unknown error: cannot find Chrome binary
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:162:17)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:231:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39
    (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-59-generic x86_64)
Cucumber steps failed
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/bin/versions/node/v4.2.1/bin/node" "/bin/versions/node/v4.2.1/bin/npm" "run" "accept"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! elos-app@0.0.1 accept: `node node_modules/chimp/bin/chimp`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the elos-app@0.0.1 accept script 'node node_modules/chimp/bin/chimp'.
npm ERR! This is most likely a problem with the elos-app package,
npm ERR! not with npm itself.

**Comment by giggio** [comment]
Chrome should already be installed. This is just the Chromedriver.
