### ISSUE TITLE
How to disable the privacy policy screen from automated tests.

### ISSUE THREAD

**Issue by abhagupta** [giggio/node-chromedriver#88]
I am trying to avoid the Chrome's Privacy Policy and Terms and Conditions screen that comes up the very first time Chrome is opened by selenium.  Is there a way to not open that everytime?  This is an Android device.. but I guess it shouldn't matter.

**Comment by giggio** [comment]
I don't know. This is just a wrapper to install and run, you should ask the Chromedriver devs.
