### ISSUE TITLE
chromedriver.exe installed by this module is not found by check in selenium-webdriver on Windows

### ISSUE THREAD

**Issue by amb26** [giggio/node-chromedriver#90]
The check in selenium-webdriver on the win32 platform is that the executable `chromedriver.exe` is on the path - https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/chrome.js#L189 - this module doesn't achieve this - instead what is put on the path is the driver `chromedriver.cmd` and a shell script `chromedriver`. Instead, `chromedriver.exe` is installed at the deeply nested path `$node_modules\chromedriver\lib\chromedriver` where it is very unlikely to be on the system path. This makes the node-chromedriver unusable for one of its main purposes, to automatically install chromedriver in such a way that the selenium-webdriver wrapper picks it up.

**Comment by giggio** [comment]
You should be able to get the path to the binary using the exported `path` property, and then configure selenium. I guess selenium is by far the most common use case for Chromedriver, I myself use it often, and it is not at all unusable, on the contrary.

**Comment by QuantumInformation** [comment]
I don't see the .exe anywhere on the download.

![image](https://user-images.githubusercontent.com/216566/33423510-f5cb82ec-d5b0-11e7-8c70-a8436fae6352.png)

I'm using it with nightwatch and it works fine on a mac:

```js
  "selenium" : {
    "start_process" : true,
    "server_path" : "./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.7.1.jar",
    "log_path" : "",
    "host" : "127.0.0.1",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "./node_modules/chromedriver/bin/chromedriver",
      "webdriver.ie.driver" : ""
    }
  }
```

Based on this repo, what would you advice to get it to work on windows?

**Comment by giggio** [comment]
@QuantumInformation looking at the `chromedriver_mac64.zip` on you directory it looks like you are on a Mac. On a Windows it will download `chromedriver_win32.zip`.

**Comment by QuantumInformation** [comment]
Ah makes sense, thx.
