### ISSUE TITLE
If install fails with proxy retry without the proxy

### ISSUE THREAD

**Issue by vschoettke** [giggio/node-chromedriver#91]
I'm using a corporate internal npm (without proxy) and have to use a proxy to access the internet. However since the npm variables are used to determine if the download should use a proxy or not, the install fails in my case (on Linux).

Maybe a retry with the usual `http(s)_proxy`/`HTTP(s)_PROXY` variables would be helpful if the download fails.

**Comment by giggio** [comment]
It is a good idea. If anyone wants to send a PR, I'll welcome it.

**Comment by Toilal** [comment]
I see there's other issues related to download of the binary. Why not using a library like [request](https://github.com/request/request) to perform the download ? see [node-sass install.js script](https://github.com/sass/node-sass/blob/master/scripts/install.js) as an example.

I have both chromedriver and node-sass dependency in my project, and behind a proxy to access the internet too. It works well for node-sass, but fails for chromedriver.

**Comment by stevehipwell** [comment]
We've got exactly the same issue.

**Comment by giggio** [comment]
We just published 2.29.1 to NPM, it probably solves the problem. I am closing the issue, please reopen if you find it does not solve it.
