### ISSUE TITLE
chromedriver install fails in mac os

### ISSUE THREAD

**Issue by longXboy** [giggio/node-chromedriver#92]
my env:
os: mac os x  10.11.6
node: 7.5.0
npm: 4.2.0

```
▶ sudo npm install
Password:

> chromedriver@2.27.3 install /Users/longxboy/Code/js/tips/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.27/chromedriver_mac64.zip
Saving to /Users/longxboy/Code/js/tips/node_modules/chromedriver/chromedriver/chromedriver_mac64.zip
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.125.203.128:443
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! chromedriver@2.27.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.27.3 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/longxboy/.npm/_logs/2017-02-15T09_01_14_669Z-debug.log
```

**Comment by luoxinvszm** [comment]
The same error on my mac：

chromedriver@2.27.3 install /Users/kingluo/git/weex/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.27/chromedriver_mac64.zip
Saving to /Users/kingluo/git/weex/node_modules/chromedriver/chromedriver/chromedriver_mac64.zip
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 64.233.187.128:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm WARN weex-vue-loader@0.2.8 requires a peer of css-loader@* but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.27.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.27.3 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kingluo/git/weex/npm-debug.log

**Comment by giggio** [comment]
Can you try chromedriver@2.27.2 and see if it works?

**Comment by monkindey** [comment]
> Downloading https://chromedriver.storage.googleapis.com/2.27/chromedriver_mac64.zip

I also suffer this problem, it's because the GFW(Great Firewall of China). you can't access the google site unless use the proxy.

ip & port is your proxy
```shell 
http_proxy ip:port yarn add chromedriver
```

It' work for me, hope work for you

**Comment by giggio** [comment]
Ok, I'll close the issue, then.
