### ISSUE TITLE
Not downloading the latest version

### ISSUE THREAD

**Issue by doberkofler** [giggio/node-chromedriver#93]
Two quick questions:

1) Is it possible, that node-chromedriver does not (always) download the latest version?
I just (re)installed and when looking at https://sites.google.com/a/chromium.org/chromedriver/downloads the latest version is 2.28 but in my node_modules I find a 2.27.

2) Is there a way to force node-chromedriver into always updating to the latest chromedriver version?

Thank you!

**Comment by giggio** [comment]
Yes: https://github.com/giggio/node-chromedriver#versioning
