### ISSUE TITLE
installation fails on mac sierra

### ISSUE THREAD

**Issue by richardry** [giggio/node-chromedriver#94]
install.js doesn't check this platform

**Comment by giggio** [comment]
We do check for the mac. We need more info.
You can see the build passing for Mac here: https://travis-ci.org/giggio/node-chromedriver/jobs/210120774

**Comment by richardry** [comment]
only works up to 2.25.1

**Comment by giggio** [comment]
We need repro steps. I am closing the issue until we got them. When you add the repro steps let me know, so we can investigate.
