### ISSUE TITLE
Chrome Driver installation does not work on windows machine.

### ISSUE THREAD

**Issue by nvellanki** [giggio/node-chromedriver#95]
npm install chromedriver on windows machine does not open the chrome browser. It would be of great help if you can fix this issue.

**Comment by rainrivas** [comment]
What is your error exactly? I'm using it on a few windows machines (10 and 7) and the install works fine.

**Comment by giggio** [comment]
Same for me. We need repro steps. I am closing the issue until we got them. When you add the repro steps let me know, so we can investigate.
