### ISSUE TITLE
Exits silently (status = 0) if chromedriver fails to execute

### ISSUE THREAD

**Issue by discordianfish** [giggio/node-chromedriver#99]
This:
```
var chromedriver = require( 'chromedriver' );
chromedriver.start();
```

exits with 0 even if it can't execute chromedriver. In my case chromedriver is dynamically linked against different libraries and therefor can't get executed:
```
# ls -alh /home/user/node_modules/chromedriver/lib/chromedriver/chromedriver
-rwxr-xr-x    1 root     root        7.2M Apr 17 11:40 /home/user/node_modules/chromedriver/lib/chromedriver/chromedriver
# /home/user/node_modules/chromedriver/lib/chromedriver/chromedriver
sh: /home/user/node_modules/chromedriver/lib/chromedriver/chromedriver: not found
```

**Comment by giggio** [comment]
You can check the `chromedriver.defaultInstance` value, which will contain a `ChildProcess` object for more information.

https://nodejs.org/api/child_process.html

See: https://github.com/giggio/node-chromedriver/blob/master/lib/chromedriver.js#L6
